### ISSUE TITLE
`ligand_in_water/ligand_in_water.ipynb` example is failing on openff-docs

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-interchange#1002]
The `ligand_in_water/ligand_in_water.ipynb` notebook has been failing on openff-docs since last month.

Here's the error:

```python
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
force_field_opc = ForceField("openff_unconstrained-2.0.0.offxml", "opc.offxml")
pprint(force_field_opc["VirtualSites"].parameters[0].to_dict())
------------------


---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[11], line 2
      1 force_field_opc = ForceField("openff_unconstrained-2.0.0.offxml", "opc.offxml")
----> 2 pprint(force_field_opc["VirtualSites"].parameters[0].to_dict())

File ~/micromamba/envs/openff-docs-examples/lib/python3.10/site-packages/openff/toolkit/typing/engines/smirnoff/parameters.py:1614, in VirtualSiteParameterList.__getitem__(self, val)
   1613 def __getitem__(self, val):
-> 1614     raise NotImplementedError(
   1615         "VirtualSiteHandler does not support __getitem__ lookups due to the "
   1616         "number of values required to uniquely identify a specific parameter."
   1617     )

NotImplementedError: VirtualSiteHandler does not support __getitem__ lookups due to the number of values required to uniquely identify a specific parameter.
```

First failed build: https://github.com/openforcefield/openff-docs/actions/runs/9523828581/job/26255855720 (note that several other notebooks are failing here; the others seem to now be working)

Last successful build: https://github.com/openforcefield/openff-docs/actions/runs/9508487787/job/26209882626

See more builds here: https://github.com/openforcefield/openff-docs/actions/workflows/cookbook_preproc.yaml

Environment file: https://github.com/openforcefield/openff-docs/blob/main/devtools/conda-envs/examples_env.yml

The failure is currently being ignored, meaning that the notebook is not being rendered while it fails to build: https://github.com/openforcefield/openff-docs/blob/7fc67369329f4a25ff9ff2a355f6f8aa2e36b04d/source/_ext/cookbook/globals_.py#L97

**Comment by mattwthompson** [comment]
Yep this is related to https://github.com/openforcefield/openff-interchange/pull/991, should be good with a new release. Thanks for the info

**Comment by mattwthompson** [comment]
I think we did this in https://github.com/openforcefield/openff-docs/pull/59
