### ISSUE TITLE
Improve GROMACS export speed

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#1014]
Execution time of `Interchange.to_top` starts to become unwieldy around a few thousand atoms, or a molecule the size of a few thousand atoms. Related #516 

```python
import pathlib

from openmm.app import ForceField, PDBFile, PME
import time
from openff.interchange import Interchange

with open("times.csv", "w") as f:
    f.write("atoms,import_time,export_time\n")

for path in pathlib.Path(".").rglob("../**/*.pdb"):
    protein = PDBFile(path.as_posix())

    if protein.topology.getNumAtoms() < 50:
        continue
    if protein.topology.getNumAtoms() > 6000:
        continue

    try:
        system = ForceField("amber14-all.xml").createSystem(
            protein.topology,
            nonbondedMethod=PME,
        )
    except ValueError:
        continue

    time0 = time.time()

    interchange = Interchange.from_openmm(system=system, topology=protein.topology)

    import_time = time.time() - time0

    print(f"{import_time=}")

    # Lazy shim for https://github.com/openforcefield/openff-interchange/issues/1007
    # some of PLB has residue indices that start at -3!
    for atom in interchange.topology.atoms:
        atom.metadata['residue_number'] = 1

    time1 = time.time()

    interchange.to_top("tmp.top")

    export_time = time.time() - time1

    print(f"{export_time=}")

    with open("times.csv", "a") as f:
        f.write(f"{protein.topology.getNumAtoms()},{round(import_time, 3)},{round(export_time, 3)}\n")
```

Some rough analysis of the scaling shows that import time is roughly linear in number of atoms but (GROMACS) export time is somewhat superlinear:

```python
In [1]: import pandas

In [2]: df = pandas.read_csv("times.csv").sort_values("atoms")

In [3]: df["export_time/atoms"] = df["export_time"] / df["atoms"]

In [4]: df["import_time/atoms"] = df["import_time"] / df["atoms"]

In [5]: df
Out[5]:
    atoms  import_time  export_time  import_time/atoms  export_time/atoms
17    582        0.730        1.072           0.001254           0.001842
2     596        0.586        1.106           0.000983           0.001856
3     596        0.626        1.181           0.001050           0.001982
4     596        0.676        1.064           0.001134           0.001785
18    602        0.674        1.225           0.001120           0.002035
9    2130        2.642       12.739           0.001240           0.005981
16   2316        2.632        2.931           0.001136           0.001266
15   2423        3.367       17.347           0.001390           0.007159
0    2448        2.714       17.517           0.001109           0.007156
7    2481        3.345       17.477           0.001348           0.007044
5    2504        2.745       17.264           0.001096           0.006895
19   2634        3.180       21.583           0.001207           0.008194
1    3579        4.150       32.257           0.001160           0.009013
8    4580        5.839       76.673           0.001275           0.016741
11   4639        5.536       55.271           0.001193           0.011914
14   4670        6.702       71.968           0.001435           0.015411
13   4820        6.386       80.142           0.001325           0.016627
12   5598        6.639       98.206           0.001186           0.017543
10   5614        6.405       95.997           0.001141           0.017100
6    5804        7.315      122.810           0.001260           0.021160
```

Visually (again, rough, I'm not going for publication quality here):

![image](https://github.com/user-attachments/assets/15d6fb3c-7528-429a-889c-d2a2288a7580)

I suspect something is up with the valence terms, since scaling with number of copies of molecules is closer to linear.

**Comment by mattwthompson** [comment]
I should add a little context here: I think there's clearly something that needs to be improved here. The next step, which I haven't gotten to yet, involves taking a protein of a few thousand atoms and seeing what's taking so long. Profiling larger proteins is probably worthwhile but might take longer to diagnose the slowdown.

**Comment by mattwthompson** [comment]
For a relateively small protein of approximately 500 atoms, about a third of the execution time is taken up in `_convert_dihedrals`. I expect this gets worse with larger proteins. I suspect the poor scaling could be due in part to the poor scaling of `Topology.atom_index`, which iterates through the topology to find an atom matching the index argument. I've looked into this more in the past but I can't find the paper trail right now.

https://github.com/openforcefield/openff-interchange/blob/v0.3.28/openff/interchange/smirnoff/_gromacs.py#L414

**Comment by mattwthompson** [comment]
Okay, I found some other details that work great for many copies of small molecules. Unfortunately the same logic works poorly for single copies of large molecules, and the other approach I can think of just switches the tradeoff around.

**Comment by mattwthompson** [comment]
I found some improvements in #1018, will continue looking for some others and building out test cases. Unfortunately we're running into the time limits of isomorphism checks.

**Comment by hannahbaumann** [comment]
@mattwthompson Thank you, the changes definitely made writing out the protein much faster!
I tested it on solvated proteins and notices that with the number of water molecules the export speed again becomes very slow.
I used the same protein (SHP2) and added different number of water molecules (`modeller.addSolvent(forcefield, model='tip3p', numAdded=i)` where i's were `[1, 100, 1000, 1500, 2000]`). 
I got following export statistics (this is both `interchange.to_top` and `interchange.to_gro`:
# atoms, import time [sec], export time [sec]
8423,40.46,83.085
8720,33.563,228.43
11420,37.747,1648.549
12920,34.256,2394.696
14420,41.639,3267.656

Is there a way to also increase the speed for larger solvent boxes?

**Comment by mattwthompson** [comment]
Darn, I thought that might have regressed the speed of exporting multiple copies of the same small molecule/solvent but I didn't look closely. I used a different strategy to look up parameters but didn't benchmark solvent boxes.

Fortunately this will be easy to test - unfortunately I'm not sure if it'll be easy to diagnose. I'll update this issue when I find something out

**Comment by mattwthompson** [comment]
I was most worried that systems from SMIRNOFF force fields with solvent were going to be very slow, fortunately this does not appear to be the case:

```python
from openff.toolkit import Molecule, ForceField, Topology

import time
import numpy

water = Molecule.from_smiles("O")
tip3p = ForceField("tip3p.offxml")

for n_molecules in numpy.logspace(0, 4, 10, dtype=int):
    topology = Topology.from_molecules(n_molecules * [water])

    interchange = tip3p.create_interchange(topology)

    start = time.time()

    interchange.to_top("tmp.top")

    print(f"{n_molecules},{round(time.time() - start, 3)}")

"""
1,0.004
2,0.001
7,0.002
21,0.003
59,0.008
166,0.022
464,0.061
1291,0.182
3593,0.659
10000,3.466
"""
```

(Above is almost surely a genuine issue, though, and I suspect it's because of something that `_SimpleMolecule` does poorly that `Molecule` does well.)

**Comment by mattwthompson** [comment]
Okay, after wasting an hour not updating a test case to take in a value provided by an iterator (arguably an important detail), I can safely reproduce this in a fairly minimal setup:

* A protein + water system is prepared with OpenMM, varying the number of waters
* `Interchange.from_openmm` is used to import the system (and topology and positions)
* `Interchange.to_gromacs` is used to write GROMACS files (both topology and coordinate files)

```python
from openff.toolkit import Molecule, ForceField, Topology
from openff.interchange import Interchange
import openmm.app
import openmm.unit
import time
import numpy

for n_solvent in numpy.logspace(1, 2.3, 10, dtype=int):

    # wget -O protein.pdb https://raw.githubusercontent.com/openforcefield/protein-ligand-benchmark/a0b67b93c4f12f63a8bb417a1f6e4df4dc10c6c5/data/shp2/01_protein/crd/protein.pdb
    pdb = openmm.app.PDBFile("protein.pdb")
    forcefield = openmm.app.ForceField('amber99sb.xml', 'tip3p.xml')
    
    modeller = openmm.app.Modeller(pdb.topology, pdb.positions)
    modeller.addSolvent(forcefield, numAdded=n_solvent, ionicStrength=0.0*openmm.unit.molar, positiveIon='K+', negativeIon='Cl-',)
    system = forcefield.createSystem(modeller.topology, nonbondedMethod=openmm.app.PME)

    interchange = Interchange.from_openmm(system=system, topology=modeller.topology, positions=modeller.positions)

    start = time.time()

    interchange.to_gromacs("tmp")

    print(f"{n_solvent=},{round(time.time() - start, 3)}")

```
Out:
```
n_solvent=10,22.983
n_solvent=13,32.631
n_solvent=19,27.957
n_solvent=27,53.98
n_solvent=37,44.999
n_solvent=52,51.853
n_solvent=73,67.462
n_solvent=102,85.781
n_solvent=143,122.158
n_solvent=199,157.797
```

**Comment by mattwthompson** [comment]
With https://github.com/openforcefield/openff-toolkit/pull/1918/commits/5fe390944b10e320120f7205ab14126abc0505ef, the same export scales much better with system size and at least doesn't have a single, obvious performance bottleneck

```
n_solvent=10,13.854
n_solvent=13,14.841
n_solvent=19,15.154
n_solvent=27,14.962
n_solvent=37,14.303
n_solvent=52,14.811
n_solvent=73,14.695
n_solvent=102,16.008
n_solvent=143,17.941
n_solvent=199,20.874
```

<img width="1639" alt="image" src="https://github.com/user-attachments/assets/2c42591c-5cfb-4e01-b8ae-afc8281c203c">

**Comment by mattwthompson** [comment]
More data, which indicates quite strongly that isomorphism checks with `_SimpleMolecule` are proximal

```
n_solvent=10,13.925
n_solvent=21,14.879
n_solvent=46,15.16
n_solvent=100,15.765
n_solvent=215,23.116
n_solvent=464,24.699
n_solvent=1000,32.893
n_solvent=2154,58.219
n_solvent=4641,121.13
n_solvent=10000,273.245
```

<img width="1639" alt="image" src="https://github.com/user-attachments/assets/d37981ab-e3e1-43b2-951c-6aab8d497d39">

**Comment by mattwthompson** [comment]
0.3.29 improves some of this, but a toolkit release (with https://github.com/openforcefield/openff-toolkit/pull/1918 or something similar) will probably be needed to get this working well with solvent

**Comment by mattwthompson** [comment]
The above linked PR is merged, with some luck this will be much better after the next toolkit release

**Comment by hannahbaumann** [comment]
Awesome, thank you so much @mattwthompson ! I will try it out!

**Comment by mattwthompson** [comment]
I think ~80-90% of the speedup will come from a toolkit release - this would be version 0.16.3 or 0.17. We'll make loud noises when that lands, but I'm unsure of the timeline now

**Comment by mattwthompson** [comment]
`openff-toolkit >=0.16.3`, launched last night, should include all of the changes we've gotten through so far, and hopefully makes these GROMACS cases not unbearably slow

**Comment by mattwthompson** [comment]
Closing this for now since there's nothing concretely actionable here, but some of this info might still be useful in the future.
