### ISSUE TITLE
Status of vacuum simulations in GROMACS

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#1029]
**Description**
Recent (~2020 onwards) versions of GROMACS do not properly support vacuum simulations. The developers [are aware of this](https://gitlab.com/gromacs/gromacs/-/issues/3526) and how it has been a limitation for its use in force field development. Users [generally work around this by setting the box](https://gromacs.bioexcel.eu/t/vacuum-simulations-in-gromacs-2020/7249) to be some arbitrarily large value, but this is a hack and has downsides.

This is a little downstream of Interchange[^1] but we run into it in tests and can't get around it as long as we want a `.to_gromacs` method that also includes the `.mdp` file. Currently, these files are written out but the user is warned about this issue and [arbitrarily sets the box vectors](https://github.com/openforcefield/openff-interchange/blob/v0.3.29/openff/interchange/interop/gromacs/export/_export.py#L471-L479) to be a 5 nanometer cube. I'd like to move to a cleaner solution with the behavior changes afforded to us in the 0.4 release, of which we have thought of a few options in this case. **In the case of a non-periodic `Interchange`, i.e. one without box vectors defined, we could:

1. Leave as-is
2. Do not write (any) GROMACS files if the system is periodic
3. Do not write some (`.mdp` and `.gro`?) files, but write other (`.top` ?) files
4. Write any files, expecting the simulations themselves to crash, and just document this quirk

Josh @Yoshanuikabundi [brought in several useful details](https://github.com/openforcefield/openff-interchange/pull/1027#issuecomment-2276872082) for context:

* Users could install old (2019 or prior) versions which have support
* GROMACS itself may add support back in a future release

These generally support the case for (4), which I think is their preference. I think I like that option as well, but I'd be fine with (2) or (3). As long as there's some error raised in this ~unsupported use case, I'm happier.

[^1]: Strictly speaking, it's fine to write out [`pbc = no`](https://manual.gromacs.org/documentation/2018/user-guide/mdp-options.html#mdp-value-pbc=no), but then trying to use _use_ it requires `cutoff-scheme = group` which is unsupported ... but confusingly a [allowed setting](https://manual.gromacs.org/documentation/2020/user-guide/mdp-options.html#mdp-value-pbc=no).

**Comment by mikemhenry** [comment]
cc @hannahbaumann

**Comment by davidlmobley** [comment]
Would love for @mrshirts to weigh in on this. I DO still want .gro files in this case, so would probably prefer warnings/documentation (e.g. option 4).  

One of the things I like about GROMACS is that I can usually get it to do what I want when I know what I'm doing. I'd hate for us to take that ability away from people. Hopefully GROMACS will re-add support for this in the future.

**Comment by davidlmobley** [comment]
(And yes, I arbitrarily set box to large value.)

**Comment by mattwthompson** [comment]
Just to clear things up, setting the box to an arbitrarily large value to "trick" GROMACS into running vacuum simulations with PBC/PME/etc will also "trick" Interchange into doing the same thing. The only cumbersome part is you defining that box as a user, but that workflow which currently works wouldn't be affected by any of the proposed changes here.

I confusingly skipped over calling out this detail and edited the first comment above to make this explicit.

**Comment by mattwthompson** [comment]
In 0.4.0, `Interchange.to_gro` (and by extension `Interchange.to_gromacs`, which calls it) will simply raise an error if `Interchange.box_vectors == None`.

If GROMACS supports "proper" vacuum simulations, especially with the sort of non-bonded settings we commonly use, we can revisit this. Until then, the recommendation is simply to use an arbitrarily large box like Mobley's group and others typically do. AFAIK this has some performance downsides, but that shouldn't be an issue for things like single molecules in a pseudo-gas phase, and some possible numerical errors with PME errors. But small electrostatics errors are par for the course in molecular simulation
