### ISSUE TITLE
Protein water systems

### ISSUE THREAD

**Issue by lwhitm1** [openforcefield/openff-interchange#1036]
**Description**
Please describe what you are trying to do, what you have done so far, and how Interchange can enable your work.

I modified the protein-ligand-water sytems tutorial in hopes of preparing my input files for subsequent gromacs simulations. I have replicated the same behavior as visualized in the tutorial-the issue is that the protein doesn't actually seem to be in the box (ovito, vmd, and pymol all show protein outside of box). I am not sure how to fix it/ how to ensure that the protein is inside of the box with the water. 

[protein-water-test.zip](https://github.com/user-attachments/files/16638289/protein-water-test.zip)

**Comment by mattwthompson** [comment]
Here's what I see when I look at `hmr.gro`:

<img width="1912" alt="image" src="https://github.com/user-attachments/assets/0a7253d1-8bbe-4230-936a-d404cf0c4d2e">

I get that it looks funny to have the protein in a different periodic image, but this is probably fine. Remember [how periodic boundary conditions work](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#how-do-periodic-boundary-conditions-work); the protein outside of the box will be imaged back into the simulation box when calculating forces, etc. You can probably run simulations with this starting point just fine, but if you want better visualizations there are tools that you can use to post-process the trajectories such that everything is in one box (with options for ensuring the molecules are whole, etc.)

For GROMACS you might find it easiest to use `gmx trjconv` but there are also post-processing like MDTraj that can do this. Here's a pretty minimal example that moves the protein around some periodic images to (partially) put it in the box - but again this is just to make it look different, the physics should be the same

```
$ gmx grompp -f default.mdp -c hmr.gro -p hmr.top -o hmr.tpr -maxwarn 1  # use any MDP file that will compile it down
...
$ echo 0 | gmx trjconv -f hmr.gro -pbc mol -o back-in-the-box.gro -s hmr.tpr  # see different options for -pbc
```

<img width="1912" alt="image" src="https://github.com/user-attachments/assets/25c462be-8016-4547-8659-9f844848b06d">
