### ISSUE TITLE
[DOCS] Document HMR virtual site limitation

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-interchange#1055]
**Description**

Virtual sites are not currently allowed when doing HMR, however there is no documentation at the "to_openmm_system" docstring level (or elsewhere as far as I can tell). This means you have to encounter the error to know the limitation.

https://github.com/openforcefield/openff-interchange/blob/57dd53aca23c0a038b09c6d2a26911388a4e64d8/openff/interchange/interop/openmm/__init__.py#L183-L187

**The ask**

A little bit more docstring docs here: https://github.com/openforcefield/openff-interchange/blob/57dd53aca23c0a038b09c6d2a26911388a4e64d8/openff/interchange/interop/openmm/__init__.py#L56-L57

**Comment by mattwthompson** [comment]
This is likely being skipped over in favor of #1080, in which support is added.

Note this only applies to OpenMM, since it's the only export that supports HMR right now. We could add HMR GROMACS and other exporters if users seek them

**Comment by mattwthompson** [comment]
Will not be a limitation in 0.4.1
