### ISSUE TITLE
[ENH] add hydrogen_mass and ewald_tolerance to `to_openmm_simulation`

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-interchange#1060]
**Description**

This is not really a need (to me), mostly something I came across whilst debugging some packmol stuff.

The `to_openmm_simulation` method doesn't allow you to apply HMR, or set the ewald tolerance, depending how the intended user experience, it may be worth adding these.

See: https://github.com/openforcefield/openff-interchange/blob/57dd53aca23c0a038b09c6d2a26911388a4e64d8/openff/interchange/components/interchange.py#L596-L602

**Comment by mattwthompson** [comment]
Yep, this would be a good change. Quite the hefty function signature afterwards

**Comment by mattwthompson** [comment]
ab7ff93b8a1c2c251169fc0cf22fe05c8ef7caaf
