### ISSUE TITLE
Interop: Apply separate force fields to different portions of a topology

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#129]
Use cases:

* Apply a separate force field to a ligand and protein
* In a mixture of organic liquids, apply separate force fields to either component

Note that applying separate force fields to any chemically bound components is outside the scope of an initial implementation, but a use case that should be covered in the future.

It's unclear to me at the moment if there should be one solution along the lines of system combination or two similar routes to the same result.

**Comment by mattwthompson** [comment]
Something to consider is that, when mixing two force fields from a line (i.e. Parsley), each SMIRKS in a potential handler is not guaranteed to be unique if not tracking the force field each is associated with. The SMIRKS patterns between versions of Parsley are mostly the same, and there is plenty of overlap between those and smirnoff99Frosst.

Maybe the best way to handle this is also track the source force field in the `PotentialKey` objects.

**Comment by mattwthompson** [comment]
The `__add__` functionality added in #148 may or may not do this clearly. I have not tested it  yet. The Parsley + GAFF/ff19sb case should be mostly covered by testing if Parsley + Foyer-style force fields can co-exist.

**Comment by j-wags** [comment]
I think this is a holdover from the days when we thought that we could have a "pre-parameterization interchange" - Like, we could add two unparameterized molecules loaded from different places, and later apply a FF to them. We decided at some point that Interchanges would strictly be "post-parameterization", and in that context I think this ticket is totally closed. If there's a use case I'm not imagining here, folks can reopen this/open a new issue.
