### ISSUE TITLE
Don't include empty valence handlers

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#196]
## Description

The `System.from_smirnoff` method will in cases create empty handlers if a molecule has no slots of a given type that need to be filled but the force field contains parameters for that slot type. An example of this is formaldehyde which does not contain any proper dihedrals, but the resulting `System` object contains an empty `SMIRNOFFProperTorsionHandler`.

This is mainly just a minor nuisance factor and I don't feel too strongly either way about keeping the empty handlers or not.

**Comment by mattwthompson** [comment]
I think this has been resolved; please re-open if that is not the case.
