### ISSUE TITLE
Found bug in gromacs top writer 

### ISSUE THREAD

**Issue by daico007** [openforcefield/openff-interchange#224]
When working on debugging #182, I found a bug in the internal gromacs writer. Short summary: when writing out the `top` file, we realize some entries in the `pairs` section are duplicated 

Code to reproduce the issue 
```
benzene = Molecule.from_file('openffsystem/openff/system/tests/files/foyer_test_molecules/benzene.sdf')
off_bio_top = OFFBioTop.from_molecules(benzene)
off_bio_top.mdtop = md.Topology.from_openmm(off_bio_top.to_openmm())
oplsaa = foyer.Forcefield(name='oplsaa')
off_system = from_foyer(off_bio_top, oplsaa)

off_system.positions = benzene.conformers[0].value_in_unit(omm_unit.nanometer)

off_system.box = [4, 4, 4]
off_system.to_top('benzene.top')
```
Output: the pair 1-4 and 3-6 got repeated twice. 
<img width="505" alt="Screen Shot 2021-06-17 at 17 25 26" src="https://user-images.githubusercontent.com/43968221/122474388-c145a180-cf88-11eb-8439-4d022dbb916a.png">

**Comment by mattwthompson** [comment]
@daico007 to double-check my back-of-the-envolope math, how many 1-4 pairs should be found in a benzene molecule?

**Comment by daico007** [comment]
The top file written by parmed has 1 entry for each

**Comment by mattwthompson** [comment]
I think there should be 21; 3 for the 3 unique 1-4 C-C pairs, 6 for the H-H, and 12 for the C-H I can find. Double-counting carbons should give 24, not 23, which confuses me.


I tried to minimally reproduce this with benzene, comparing the toolkit's `Moleucle.nth_degree_neighbors` behavior to the `_iterate_pairs` used here. This should run without error:

```python3
import mdtraj as md
from openff.toolkit.topology import Molecule

from openff.interchange.components.mdtraj import _iterate_pairs, _store_bond_partners

benzene = Molecule.from_smiles("c1ccccc1")
mdtop = md.Topology.from_openmm(benzene.to_topology().to_openmm())
_store_bond_partners(mdtop)

# This implementation double-counts some C-C bonds
assert len([*_iterate_pairs(mdtop)]) == 24

# The corresponding implementation in the toolkit does not
assert len([*benzene.nth_degree_neighbors(n_degrees=3)]) == 21
```

so I would expect that fixing `_iterate_pairs` to give the correct 21 should fix energies in a benzene test case. What doesn't make sense to me is how 23 could be written out.

**Comment by daico007** [comment]
Oh, sorry I misunderstood your question. Yeah parmed written 21 pairs (so I think the correct number that we expect here)

**Comment by mattwthompson** [comment]
Okay, this turned out to be a little trickier than I expected, since the MDTraj API doesn't provide a way to crawl through a molecular graph as easily as the toolkit does. I have a patch in place that I'll push in a few minutes if everything passes locally. I think it should fix this, but I'll ask you to review it @daico007 

The problem was likely that this de-duplication failed, but I'm not quite sure how:
https://github.com/openforcefield/openff-interchange/blob/3803eb81b42015df2a0ee075a76e0373d319eb2a/openff/interchange/interop/internal/gromacs.py#L312-L313

**Comment by mattwthompson** [comment]
Thanks again for finding this @daico007 @justinGilmer!
