### ISSUE TITLE
Design: Term-specific TopologyKey subclasses?

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#264]
After adding a `bond_order` field to `TopologyKey`, most of its fields are now optional and won't be set in most cases. I'm thinking of possibly making more specific classes so that some of these are turned "off" when they'll never be used. Another side effect is that the `mult` field is used differently in different cases; I think in torsions it represents the nth term in the summation, but something totally different when dealing with partial charges.

```python3
class TopologyKey(DefaultModel):
    atom_indices = Field(...)  # as is

class BondKey(TopologyKey):
    bond_order = Field(...)

class AngleKey(TopologyKey):
    # basically do nothing

class ProperTorsionKey(TopologyKey):
    multiplicity= Field(...)
    bond_order = Field(...)

class ImproperTorsionKey(TopologyKey):
    # not sure
```

For other things that we haven't come across (I don't know, maybe Urey-Bradleys, CMAPs, or exotic electrostatics routines) this would allow us to create new structures in the future without dumping more optional fields into things that don't need them. We already created a `VirtualSiteKey` because they are so different from "atom" topology groupings.

I haven't thought about the non-bonded cases much, but it might be nice to keep the electrostatics gunk contained only to a class or two that would actually use it.

cc: @SimonBoothroyd

**Comment by SimonBoothroyd** [comment]
Thanks for thinking this through @mattwthompson - I'll try and give some feedback next week!

**Comment by mattwthompson** [comment]
This has been implemented basically as-is; in some cases the base class is used in lieu of one more tailored to a specific case, but it's fine most of the time since the check is usually just comparing the atom indices.
