### ISSUE TITLE
"meta" handlers

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#34]
The prototype of a `PotentialHandler` for bonds bypasses several issues, one of them being that parts of a force field are not always able to operate independently of each other. The most difficult example of this, for us, is electrostatics, in which one could think of a "meta" handler (`ElectrostaticsMetaHandler`, or something) that itself includes potentially several handlers (library charges, AM1-BCC, charge increments, etc.). (There may also be a meta handler for VDW terms, in which atoms and virtual sites are treated differently). This would provide one interface to the results of the child classes, i.e. a single place to get the charges that a force field would ultimately apply to the system.

It's unclear to me if this class should inherit from `PotentialHandler` or just be another instance of it. I learn toward the former, as a meta handler won't have individual parameters of its own, and therefore it doesn't make sense to expose methods that rely on that data.

**Comment by j-wags** [comment]
I think meta-handlers are inevitable for the `ForceField`/`ParameterHandler` stacks, and I don't think they're a bad thing. But maybe I'm not seeing the full picture here -- What information would a partial-charge-assignment `PotentialHandler` have that that `ParameterHandler` wouldn't? Is it just the results of eg. AM1BCC calculations on a molecule, and a pointer to the `ToolkitAM1BCCHandler` class??

Maybe the more general question is, if we put a hierarchy into the `ForceField`/`ParameterHandler` stack, must `System`/`PotentialHandler` also get that hierarchy?

Separately, one additional consideration might be what to do when two handlers need to see the same contents -- For example both `Electrostatics` and `GBSA` probably want to use the same charges. What will be the best setup there?

**Comment by mattwthompson** [comment]
`Potential` handler objects also expose different from `ParameterHandler` objects in that the parameter sources are maintained (and not duplicated in memory when applied many times into a system). This doesn't apply to `ToolkitAM1BCCHandler`  as the force field does not own the "parameters" of that method, but it would apply to cleaner methods like library charges, charge increments, and possibly graph net charges.

> Maybe the more general question is, if we put a hierarchy into the `ForceField`/`ParameterHandler` stack, must `System`/`PotentialHandler` also get that hierarchy?

Maybe they don't need to be stored in a hierarchy, but it seems like a natural way to group parameters, i.e. for fitting a force field that exposes all BCCs, you'd want to be able to access that relevant handler and its differentiable representation, not just grab the partial charges that result from applying it. But you wouldn't want it floating around without an association with the `ElectrostaticsHandler` meta handler, I don't think, as they're not meant to act independently of each other. Also meta handlers may not "do" anything themselves, but only serve to collect information from objects they "own."

> Separately, one additional consideration might be what to do when two handlers need to see the same contents -- For example both `Electrostatics` and `GBSA` probably want to use the same charges. What will be the best setup there?

If `GBSAHandler` only cares about the final charges, that would favor an implementation that collects all partial charge methods into a single high-level electrostatics meta handler, which does everything it needs to do once and stores its outputs somewhere. If another handler needs only one part of it, i.e. only custom BCCs but not other charge methods, then it should be able to access only the results of that handler (`PotentialHandler.potentials`)

**Comment by mattwthompson** [comment]
#200 implemented something along these lines for electrostatics. It remains to be seen how virtual sites will be handled

**Comment by mattwthompson** [comment]
There isn't much of a need for this now; the hierarchy of components within other components isn't common enough that they can't be dealt with as special cases.
