### ISSUE TITLE
Missing `__init__.py` files

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#367]
## Description

Certain submodules in the codebase are missing an `__init__.py` file (e.g. `openff.interchange.unit_tests.drivers`). These should probably be included to avoid possible issues with [namespace packages](https://www.python.org/dev/peps/pep-0420/), as well as to provide docstrings for the submodule itself.

**Comment by mattwthompson** [comment]
I think this is resolved, and I also added a linter (https://github.com/openforcefield/openff-interchange/pull/416) to ensure no more are added. Without it, I'm liable to un-resolve this issue
