### ISSUE TITLE
Expose `Interchange` at the top level

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#371]
## Description

Currently the main object of this package, `Interchange` is importable as `from openff.interchange.components.interchange import Interchange`. It may make sense to expose this at the top level `__init__` so you can instead just do `from openff.interchange import Interchange`

**Comment by SimonBoothroyd** [comment]
You may also want to consider just removing the `components` nesting altogether, as it's a bit confusing as to what a `component` is.

It may be clearer to have a `handlers` submodule containing `smirnoff`, `base`, `foyer`, have `interchange` as a top level `_interchange` submodule with its members exposed via the top level `__init__`, move `mbuild` to `interop`?, and move `mdtraj` to `_mdtraj` as it seems to be just a placeholder that will be removed when the toolkit has the required features?

**Comment by SimonBoothroyd** [comment]
You could then also consider moving the `XXXKey` classes from `models` which is a bit nebulous into `_interchange`

**Comment by mattwthompson** [comment]
Not sure when this was done but you can now

```python3
from openff.interchange import Interchange
