### ISSUE TITLE
Clean-up `openff.interchange.utils`

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#372]
## Description

It seems that `openff.interchange.utils` contains a few mismatch utilities which maybe shouldn't be included in the public API, and that are probably now provided by other packages in the ecosystem.

In particular:

* should `pint_to_openmm`, `_unwrap_list_of_pint_quantities` live in `openff-units`?
* could `get_test_file_path`, `get_test_files_dir_path`,  be moved to a common `openff.interchange.tests._utils` submodule (see #368)
* `get_nonbonded_force_from_openmm_system` and `get_partial_charges_from_openmm_system` should probably live in `interop.openmm`? The type hints should probably also be imported under a `TYPE_CHECKING` if statement to remove the hard `openmm` dependency.
* `compare_forcefields` should probably either live in the toolkit or be removed as it doesn't seem to be used within `interchange`.

**Comment by mattwthompson** [comment]
This file doesn't seem to exist anymore - looks like everything was removed in #373
