### ISSUE TITLE
Docs builds broken

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#378]
@Yoshanuikabundi if you have some bandwidth in the next week or so, could you take a look at the RTD builds? One such broken [build](https://readthedocs.org/projects/openff-interchange/builds/15845380/). The warnings are confusing (why is just one of the submodules not found by autosummary?) and it's not clear at all from the log why the build _fails_, assuming that the autosummary warnings are not supposed to be fatal.

I can build locally using the instructions in the  developer docs (including making a whole new environment) and things look okay on first pass.

**Comment by Yoshanuikabundi** [comment]
Yeah autosummary errors suck. It sometimes reports a module as not existing when actually all that happened was python threw an error in parsing it. That the local build works is surprising. Taking a look now!

**Comment by mattwthompson** [comment]
Thanks Josh. You've probably come across it already but FTR #373 or some related PR moved a ton of the `/*_tests/` modules into a new `/tests/*_tests`. I [took a stab](https://github.com/openforcefield/openff-interchange/blame/main/docs/conf.py#L75) and IIRC that change made my local build work fine. I couldn't see any obvious reason the [RTD config](https://github.com/openforcefield/openff-interchange/blob/main/.readthedocs.yml) would differ.

**Comment by Yoshanuikabundi** [comment]
Opened #382 which solves this one. I'm guessing you had foyer available in your local build? If not, then it probably warned on your local build but didn't propagate that warning into a failure. RTD does so propagate so that this stuff gets noticed and fixed :)

**Comment by mattwthompson** [comment]
> I'm guessing you had foyer available in your local build?

In my normal development build, yes, but I did make a docs env for tinkering with this.

>  probably warned on your local build but didn't propagate that warning into a failure

This sounds right - I'm conditioned to ignore warnings, and this is an effect of that anti-pattern.
