### ISSUE TITLE
Incorrect Version Returned

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#429]
The `.gitattributes` file points to `openff/system/_version.py` rather than `openff/interchange/_version.py` which leads to the released packages having an incorrect version string. In an env with 0.1.4 installed:

```python
>>> import openff.interchange
>>> openff.interchange.__version__
'0+untagged.39.g5f75eae.dirty'
```

**Comment by mattwthompson** [comment]
Oh wow, nice catch. Thanks!
