### ISSUE TITLE
Best practices for parametrising a small molecule using OpenFF

### ISSUE THREAD

**Issue by msuruzhon** [openforcefield/openff-interchange#461]
Hello,

I have a soft question about the current status of the repo. The OpenFF parametrisation examples that I have seen all use `ParmEd`, but on the other hand the `openff-interchange` repo is much more active in terms of development. Which package is currently the canonical/most robust one to use for writing out an OpenFF AMBER/GROMACS topology from an OpenMM system?

Many thanks.

**Comment by mattwthompson** [comment]
Hi @msuruzhon,

Currently there is no canonical way to write to AMBER or GROMACS files using stable OpenFF tools. Going to these files through ParmEd & OpenMM has historically been the best woarkaround (often the only possible one) but there are a few rough edges by nature of converting between incompatible high-level object models multiple times. Interchange's exports to these files is experimental but under active development. I can't recommend it for publication-quality work, but if you are interested in tinkering with experimental software you are more than welcome to use Interchange and would gladly welcome feedback on your experiences!

Development right now is focused on a new release (v0.2.x) which is associated with a new version of the OpenFF Toolkit (v0.11.x) which unfortunately doesn't have a release date yet. Again if you are interested in testing pre-release software I can guide you to installation instructions, but I cannot recommend using unreleased software for scientific studies.

> ... parametrising a small molecule

It's worth pointing out that this is a use case that is key to OpenFF and, depending on what else is in your simulation box, the most straightforward to support. Knock on wood: parametrizing a small molecule is the most thoroughly-tested use case of Interchange.

> ... from an OpenMM system

This is not a supported use case at the moment. While it's on the roadmap as a target after a few current objectives are met, we do not view it as a key workflow. Our primary focus is parametrizing a molecule (in the [OpenFF object model](https://docs.openforcefield.org/projects/toolkit/en/stable/api/generated/openff.toolkit.topology.Molecule.html#openff.toolkit.topology.Molecule), for which there are [many pathways](https://docs.openforcefield.org/projects/toolkit/en/stable/users/molecule_cookbook.html) to get there) with a SMIRNOFF-style force field (again with an object [model we provide](https://docs.openforcefield.org/projects/toolkit/en/stable/api/generated/openff.toolkit.typing.engines.smirnoff.forcefield.ForceField.html#openff.toolkit.typing.engines.smirnoff.forcefield.ForceField)) into an `Interchange` object, which can then be converted/written out to OpenMM or experimentally GROMACS, AMBER, LAMMPS. If your focus is small molecules, my guess if you have a SMILES string, SDF file, etc. available so this should not be an issue.

**Comment by msuruzhon** [comment]
Thank you for the reply @mattwthompson. As far as I understand this means that no intermediate OpenMM system is then used in Interchange, is this correct?

Also, just to be clear, if one is strictly interested in parametrised small molecules for use in MD engines other than OpenMM (e.g. AMBER/GROMACS), which approach would you recommend as _currently_ the most reliable one for a production simulation?:

- OpenFF with ParmEd conversion to AMBER/GROMACS
- OpenFF with Interchange conversion to AMBER/GROMACS
- GAFF with other tools for conversion

Many thanks.

**Comment by mattwthompson** [comment]
> no intermediate OpenMM system is then used

Correct, `openmm.System()` is only called if that's the export that's targeted. For other exports, everything is stored in data models internal to Interchange.

> which approach would you recommend as _currently_

Of those I'd have to pick the first one; you may have already come across some of [these](https://docs.openforcefield.org/projects/toolkit/en/0.10.6/examples.html) examples, probably [this](https://github.com/openforcefield/openff-toolkit/tree/stable/examples/using_smirnoff_in_amber_or_gromacs) one in particular (or quite possibly you're already familiar with the API points that handle those conversions).

Interchange conversion to AMBER[^1]/GROMACS is highly experimental in the current releases (Interchange 0.1.x using OpenFF Toolkit 0.10.x) and less-but-still experimental in the upcoming releases. Those releases aren't out yet though, so those don't help in the context of this question.

The last option is somewhat a scientific question and less of a software one - certainly I'm biased in that I'd like you to try out the OpenFF force fields, but to asses if they're better than GAFF for your use case I'll point you to benchmarks ([Parsley](https://openforcefield.org/community/news/general/introducing-openforcefield-1.0/), [Sage](https://openforcefield.org/community/news/general/sage2.0.0-release/)) and papers ([Parsley](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.1c00571), Sage paper still in the works). Sage trades blows with GAFF but one may be more appropriate depending on the property you're after.


In terms of software, I'm less familiar with Amber infrastructure than OpenMM and GROMACS, but GAFF is so broadly used that there are a handful of options; I think sticking with the Amber tools and using ParmEd for interoperability is probably what the Amber developers would recommend. (If in the future you had any reason to want to use GAFF more closely to OpenMM, [`openmmforcefields`](https://github.com/openmm/openmmforcefields#using-amber-gaff-1x-and-2x-for-small-molecules) is a good option.)

 I should also make it clear that ParmEd is not abandoned or anything, it's just not funded at the moment and our efforts here are in part to keep our infrastructure streamlined under one roof. If you find bugs while using ParmEd there will likely be somebody around to fix them there.

Sorry that Interchange is not totally live for your use case at the moment - hopefully it will be in a few weeks or months!

[^1]: I'm never sure if AMBER/Amber is all-caps or not

**Comment by msuruzhon** [comment]
Thank you for the helpful answer @mattwthompson, I think I will be sticking to `ParmEd` for the time being, but I am looking forward to eventually using Interchange!
