### ISSUE TITLE
Slow interchange object generation for large systems 

### ISSUE THREAD

**Issue by tlfobe** [openforcefield/openff-interchange#471]
Hello! Owen told me @mattwthompson wanted me to post an issue, so here it is!

I'm currently using the openff-toolkit to parameterize some foldamer oligomers (ranging from 197-337 atoms). Using the example jupyter-notebook [here](https://github.com/openforcefield/openff-toolkit/blob/master/examples/using_smirnoff_in_amber_or_gromacs/export_with_interchange.ipynb) I've been assigning parameters to for a variety of these oligomers, but find for the larger systems the AM1BCC partial charges take a really long time (like an hour or more) and the `Interchange` object creation also takes a really long time.

I figured I could share a minimum use case for the systems I'm trying to parameterize.

I made a workaround for the larger molecules by changing the default OpenEye maximum atoms allowed for AM1BCC charges by changing line 2063 in [openeye_wrapper.py](https://github.com/openforcefield/openff-toolkit/blob/97462b88a4b50a608e10f735ee503c655f9b64d3/openff/toolkit/utils/openeye_wrapper.py#L2065) to:
```
                oe_charge_method = oe_charge_method(maxAtoms = 500)
```
This allows OpenEye to use AM1BCC to calculate charges for more than 300 atoms which is normally the default value.

I've attached the .mol file and .pdb file I used to get these slow times below (I had to add the .txt extension to upload them, sorry!). These were both generated in Avogadro2 and had structures optimized using the OpenBabel plugin in Avogadro2.
[terphenyl_pop_octamer.mol.txt](https://github.com/openforcefield/openff-interchange/files/8962540/terphenyl_pop_octamer.mol.txt)
[terphenyl_pop_octamer.pdb.txt](https://github.com/openforcefield/openff-interchange/files/8962541/terphenyl_pop_octamer.pdb.txt)

Below is a part of the the jupyter notebook I'm using to assigning parmameters. I use `molecule.compute_partial_charges_am1bcc()` and instead of having `ForceField.create_openmm_system` automatically calculate them using default values since `AM1BCCELF10` doesn't have an option to change the number of atoms it can use in OpenEye.

---

```python
# Create the OpenFF Topology.
off_topology = Topology.from_openmm(
    omm_topology, unique_molecules=[oct_pop]
)

```

```python
# Modified OpenFF to increase maxAtoms for AM1BCC method to 500 atoms
oct_pop.compute_partial_charges_am1bcc()
```

### Preparing an OpenFF ForceField

Once the `ForceField` class is imported, the only decision to make is which force field to use. An exhaustive list of force fields released by the Open Force Field Initiative can be found [here](from openff.toolkit.typing.engines.smirnoff import ForceField
).

Here we will use force field from the "Sage" line.

```python
forcefield = ForceField("openff-2.0.0.offxml")
```

### Preparing an OpenMM System

Once a force field and topology have been loaded, an `openmm.System` can be generated natively with the OpenFF Toolkit.

```python
omm_system = forcefield.create_openmm_system(off_topology, charge_from_molecules = [oct_pop])
omm_system
```

    <openmm.openmm.System; proxy of <Swig Object of type 'OpenMM::System *' at 0x7f439e930330> >

### Preparing an Interchange object

To exports to engines other than OpenMM, we will make use of the [Interchange](https://openff-interchange.readthedocs.io/) project. There is a high-level `Interchange.from_smirnoff` function that consumes OpenFF Toolkit and ForceField objects and produces an `Interchange` object which can then be exported to formats understood by other molecular simulation engines. This extra step is needed to provide a clean interface between _applied_ parameters and engines. Note also that this step does not require an OpenMM System to be generated; `ForceField.create_openmm_system` does not need to be called to use Amber and GROMACS.

```python
from openff.interchange.components.interchange import Interchange

interchange = Interchange.from_smirnoff(
    force_field=forcefield,
    topology=off_topology,
)
interchange.positions = pdbfile.positions
interchange
```

---
The last code cell included here is where Interchange takes a really long time, I've had it running now for propably an hour.

**Comment by tlfobe** [comment]
And these are some warnings I was getting out from the last code cell
```
/home/tfobe/anaconda3/envs/terphenyl/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/tfobe/anaconda3/envs/terphenyl/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/tfobe/anaconda3/envs/terphenyl/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/tfobe/anaconda3/envs/terphenyl/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
```

**Comment by mattwthompson** [comment]
Hi @tlfobe thanks for the thorough report - I'll dig into it a bit more tomorrow but my first impression is basically that you're doing everything right and hitting an unavoidable step of charging large molecules with an AM1-based method. There's no getting around [^1] that computation [^2] but the shortcut I can recommend is that you only do it _once_ and save the output. After you call `oct_pop.compute_partial_charges_am1bcc()` but _before_ you call `ForceField.create_openmm_system` / `Interchange.from_smirnoff`, save out that object to disk. It'll have AM1-BCC ELF10 partial charges on that object and when you load that in the next time, you'll be able to skip that hour-long step. This won't get around the need to run it once per unique molecule in your project, but it will get around needing to run it multiple times; if your set of oligomers is known you should be able to generate a library in a few hours or days. (If you're generating new unique oligomers on the fly that might not work so well for obvious reasons.)

SDF is probably the best format for this; ignoring the data, something like


```python3
In [1]: from openff.toolkit import Molecule

In [2]: oct_pop = Molecule.from_file("/Users/mattthompson/Downloads/terphenyl_pop_octamer.mol.txt", file_format="mol")

In [3]: oct_pop.assign_partial_charges(partial_charge_method='gasteiger')  # Replace with 'am1bccelf10' and wait an hour ...

In [4]: oct_pop.to_file('terphenyl_pop_octamer_charges.sdf', file_format='sdf')

```

Now, you have the result of that long AM1 calculation saved and can load it up in a few ms:
```python3
In [5]: Molecule.from_file("terphenyl_pop_octamer_charges.sdf", file_format='sdf').partial_charges
Out[5]:
array([ 0.062521  ,  0.054548  ,  0.149598  ,  0.064346  ,  0.062459  ,
        0.052869  ,  0.062521  ,  0.064346  ,  0.062459  ,  0.062106  ,
        0.05461   ,  0.062371  ,  0.151544  ,  0.062382  ,  0.062106  ,
        0.062371  ,  0.064954  ,  0.064346  ,  0.062382  ,  0.062521  ,
       -0.042445  ,  0.062371  ,  0.062382  ,  0.062521  ,  0.062382  ,
        0.064954  ,  0.062371  ,  0.062106  , -0.042445  ,  0.064346  ,
        0.054548  ,  0.062371  ,  0.062106  ,  0.062382  ,  0.062459  ,
        0.025728  ,  0.025728  ,  0.025728  ,  0.025728  ,  0.149598  ,
        0.062382  , -0.053696  , -0.027439  ,  0.062521  , -0.294054  ,
        0.353174  , -0.035698  ,  0.054548  , -0.053298  ,  0.062371  ,
        0.062382  , -0.056241  ,  0.025728  ,  0.025728  ,  0.025728  ,
        0.025728  ,  0.025728  ,  0.062459  ,  0.062371  , -0.042382  ,
       -0.053298  , -0.042445  ,  0.149598  , -0.30478799,  0.062106  ,
        0.064954  , -0.035698  ,  0.062382  , -0.347893  , -0.347893  ,
        0.062106  , -0.04906   , -0.035698  , -0.347893  ,  0.062521  ,
        0.062521  ,  0.062521  ,  0.062371  ,  0.062106  ,  0.045839  ,
        0.244523  , -0.27018499, -0.241331  ,  0.072088  , -0.347893  ,
        0.062106  , -0.04906   ,  0.036745  , -0.010019  , -0.051011  ,
       -0.031081  ,  0.076425  , -0.023394  , -0.00774   , -0.017262  ,
       -0.017205  , -0.053696  , -0.056241  , -0.027439  , -0.056241  ,
       -0.053696  , -0.053298  , -0.04906   ,  0.036745  , -0.04906   ,
       -0.053298  ,  0.045839  , -0.30478799,  0.244523  , -0.27018499,
       -0.023394  ,  0.076425  , -0.031081  , -0.051011  , -0.010019  ,
       -0.00774   , -0.017205  , -0.017262  , -0.053298  , -0.04906   ,
        0.036745  , -0.04906   , -0.053298  , -0.053696  , -0.05624   ,
       -0.027376  , -0.05624   , -0.053696  ,  0.244523  ,  0.047669  ,
       -0.28480399, -0.27018499, -0.023394  ,  0.076425  , -0.031081  ,
       -0.051011  , -0.010019  , -0.00774   , -0.017205  , -0.017262  ,
       -0.053298  , -0.04906   ,  0.036745  , -0.04906   , -0.053298  ,
       -0.053696  , -0.056241  , -0.027439  , -0.056241  , -0.053696  ,
        0.244523  ,  0.045839  , -0.30478799, -0.27018499, -0.010019  ,
       -0.051011  , -0.031081  ,  0.076425  , -0.023394  , -0.00774   ,
       -0.017262  , -0.017205  , -0.053696  , -0.056241  ,  0.052869  ,
        0.052869  ,  0.052869  ,  0.052869  ,  0.064954  ,  0.043026  ,
        0.043026  ,  0.043026  ,  0.043026  ,  0.052869  ,  0.052869  ,
        0.052869  ,  0.052869  ,  0.052869  ,  0.052869  ,  0.052869  ,
        0.052869  ,  0.052869  ,  0.052869  ,  0.052869  ,  0.052869  ,
        0.025074  ,  0.025074  ,  0.025074  ,  0.025074  ,  0.025074  ,
        0.025074  ,  0.025074  ,  0.025074  ,  0.025074  ,  0.025074  ,
        0.025074  ,  0.025074  ,  0.062521  ,  0.054548  ,  0.149598  ,
        0.064346  ,  0.062459  ,  0.052972  ,  0.062521  ,  0.064346  ,
        0.062459  ,  0.062106  ,  0.054548  ,  0.062371  ,  0.052869  ,
        0.062382  ,  0.062106  ,  0.062371  ,  0.064954  ,  0.064346  ,
        0.062382  ,  0.062521  , -0.042445  ,  0.062371  ,  0.062382  ,
        0.062545  ,  0.062382  ,  0.064954  ,  0.062371  ,  0.062106  ,
       -0.042445  ,  0.064346  ,  0.054548  ,  0.062371  ,  0.062106  ,
        0.062382  ,  0.062459  ,  0.025074  ,  0.025074  ,  0.025074  ,
        0.052869  ,  0.149598  ,  0.062382  , -0.053696  , -0.027439  ,
        0.062521  ,  0.025074  ,  0.052869  ,  0.025074  ,  0.054548  ,
       -0.053274  ,  0.062371  ,  0.062382  , -0.056241  ,  0.025074  ,
        0.025074  ,  0.025074  ,  0.052869  ,  0.025074  ,  0.062459  ,
        0.062371  , -0.042445  , -0.053274  , -0.042445  ,  0.149598  ,
       -0.30478799,  0.062106  ,  0.064954  ,  0.025074  ,  0.062382  ,
       -0.347893  , -0.347893  ,  0.062106  , -0.048301  ,  0.025074  ,
       -0.347893  ,  0.062521  ,  0.062521  ,  0.062545  ,  0.062371  ,
        0.062106  ,  0.045839  ,  0.29355499, -0.25923499,  0.052869  ,
        0.025074  , -0.347893  ,  0.062106  , -0.048301  ,  0.046501  ,
       -0.010019  , -0.051011  , -0.031081  ,  0.076425  , -0.023394  ,
       -0.00774   , -0.017262  , -0.017205  , -0.053696  , -0.056241  ,
       -0.027439  , -0.056241  , -0.053696  , -0.053298  , -0.04906   ,
        0.036745  , -0.04906   , -0.053298  ,  0.045839  , -0.30478799,
        0.244523  , -0.27018499, -0.023394  ,  0.076425  , -0.031081  ,
       -0.051011  , -0.010019  , -0.00774   , -0.017205  , -0.017262  ,
       -0.053298  , -0.04906   ,  0.036745  , -0.04906   , -0.053298  ,
       -0.053696  , -0.056241  , -0.027439  , -0.056241  , -0.053696  ,
        0.244523  ,  0.045839  , -0.30478799, -0.27018499, -0.023394  ,
        0.076425  , -0.031081  , -0.051011  , -0.010019  , -0.00774   ,
       -0.017205  , -0.017262  , -0.053298  , -0.04906   ,  0.036745  ,
       -0.04906   , -0.053298  , -0.053696  , -0.056241  , -0.027439  ,
       -0.056241  , -0.053696  ,  0.244523  ,  0.045839  , -0.30478799,
       -0.27018499, -0.010019  , -0.051011  , -0.031081  ,  0.076425  ,
       -0.023394  , -0.00774   , -0.017261  , -0.017205  , -0.053696  ,
       -0.056241  , -0.314758  ,  0.052972  ,  0.046196  ,  0.052972  ,
        0.064954  ,  0.043026  ,  0.043026  ,  0.043026  ,  0.043026  ,
        0.052869  ,  0.052869  ,  0.149598  ]) <Unit('elementary_charge')>

```

A slightly more elegant approach than passing the molecule through via `charge_from_molecules` is to use `LibraryChargeType`s generated from the same molecules via [`from_molecule`](https://docs.openforcefield.org/projects/toolkit/en/stable/api/generated/openff.toolkit.typing.engines.smirnoff.parameters.LibraryChargeHandler.html#openff.toolkit.typing.engines.smirnoff.parameters.LibraryChargeHandler.LibraryChargeType.from_molecule); it does basically the same thing but stores those molecule-specific partial chargers in the force field directly.


I recognize this approach isn't perfect - storing an extra copy of each molecule on disk isn't ideal - but it at least hedges the AM1 computation time down to the minimum that it can conceptually be.

[^1]: Until GCNN-based charges do everything for free
[^2]: To be honest, I didn't really think that much above ~[100 atoms](https://docs.openforcefield.org/projects/toolkit/en/topology-biopolymer-refactor/faq.html#parameterizing-my-system-which-contains-a-large-molecule-is-taking-forever-whats-wrong) even finishes!

**Comment by tlfobe** [comment]
Hey just following up! I'll make sure to save charges using what you provided above to only have to do this once! I think it's expected that AM1-BCC would take a long time for a large number of atoms, but I was confused by the Interchange running so slowly. Michael had mentioned that it's mostly just writing parameters to file in different formats, rather than doing any long calculations.

I will say I was running this over a remote filesystem, so maybe it shouldn't have taken as long as it did (I stopped the Interchange conversion after 2 or so hours). I assume since Interchange does a lot of write calls, maybe it had an issue with the remote file system. I'm trying this again with everything being stored on my local computer, so hopefully, it doesn't get stuck this time.

**Comment by mattwthompson** [comment]
How are you installing Interchange and the rest of the OpenFF Stack? Could you show me a `conda list` output? What are your typical system sizes, and have you gotten any to finish the conversion? I'd be particularly interested in rough benchmarks of, for systems of a given size, how long it takes to prepare the `Interchange` object with AM1BCC charges provided and, separately, how long it takes to write the files.


I recently found a pretty bad bug in which I was looking up the non-bonded parameters for _all_ atoms once per molecule, which makes i.e. writing out solvated systems very slow. I fixed this in #465 but I am confident there are other optimizations to be had; most of the work lately has gone to improving the OpenMM export while the GROMACS exports have been more primitive. Regardless, it should not take two hours!

**Comment by tlfobe** [comment]
So I think this issue was primarily AM1BCC charge assignment slowing things down. I did add the `charge_from_molecules = [oct_pop]` to the interchange object and that makes sure the calculating of the partial charges only happens once (and I'm now saving the partial charges to an .sdf file too)

**Comment by mattwthompson** [comment]
Hopefully we can move away from AM1 for large systems soon!
