### ISSUE TITLE
Add example(s) of single ligands with 4- and 5-site water models

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#477]
There is currently one example of a ligand in TIP3P water. This should should be expanded to include at least one water model that uses virtual sites. It could also be expanded to show its use in different engines.

**Comment by mattwthompson** [comment]
cc: @maxbonomi I hope to have [this](https://github.com/openforcefield/openff-interchange/pull/476#issuecomment-1169244346) wrapped up into a standalone example soon

**Comment by maxbonomi** [comment]
Super!

**Comment by mattwthompson** [comment]
@maxbonomi could you see if these files run for you, or at least compile into a `.tpr`? And if you're feeling really generous, recommend an MDP file and the arguments you pass to `gmx grompp` etc.? I used GROMACS for years as a PhD student but never got virtual sites working with it, and lately I'm much more familiar with OpenMM.

[system.gro.txt](https://github.com/openforcefield/openff-interchange/files/9473765/system.gro.txt)
[system.top.txt](https://github.com/openforcefield/openff-interchange/files/9473766/system.top.txt)


Here's the script I used to generate these, it's somewhat spliced from a couple of examples (see the second half of the [virtual sites](https://github.com/openforcefield/openff-toolkit/blob/0.11.0/examples/virtual_sites/vsite_showcase.ipynb) example and the [toolkit showcase](https://github.com/openforcefield/openff-toolkit/blob/0.11.0/examples/toolkit_showcase/toolkit_showcase.ipynb) for how the waters were added) and [this](https://gist.github.com/mattwthompson/c32818a000638287b70c1104724529dd) force field file, which I made by modifying an existing TIP4P file and eyeballing what's different in [TIP4P-EW](http://www.sklogwiki.org/SklogWiki/index.php/TIP4P-Ew_model_of_water)

```python3
from openff.toolkit import ForceField, Molecule, Topology
from openff.toolkit.utils import RDKitToolkitWrapper
from openff.units.openmm import from_openmm
from openmm import unit as openmm_unit
from pdbfixer import PDBFixer

from openff.interchange import Interchange

# PT-2385, https://pubchem.ncbi.nlm.nih.gov/compound/pt-2385
SMILES = "N#CC1=CC(F)=CC(OC2=CC=C(S(=O)(C)=O)C3=C2CC(F)(F)[C@H]3O)=C1"

ligand = Molecule.from_smiles(SMILES)
ligand.generate_conformers(n_conformers=1)
ligand.to_file("ligand.pdb", "pdb", toolkit_registry=RDKitToolkitWrapper())

pdb_object = PDBFixer("ligand.pdb")
pdb_object.addSolvent(padding=0.3 * openmm_unit.nanometer)

topology = Topology.from_openmm(
    pdb_object.topology,
    unique_molecules=[
        ligand,
        Molecule.from_smiles("O"),
    ],
)

topology.set_positions(from_openmm(pdb_object.positions))

sage_with_tip4p_ew = ForceField("openff-2.0.0.offxml", "tip4p-ew.offxml")

interchange = Interchange.from_smirnoff(sage_with_tip4p_ew, topology)

interchange.to_gro("system.gro")
interchange.to_top("system.top")

**Comment by maxbonomi** [comment]
Thanks @mattwthompson 
I see a few problems when creating a tpr file using [4-nvt.mdp.zip](https://github.com/openforcefield/openff-interchange/files/9555559/4-nvt.mdp.zip):

1) the atomtype VS is defined multiple times in system.top (from line 328 to 421): one should be enough ;-)
2) there are 279 non-matching atom names in system.top/system.gro. Here a few examples
    atom name 43 in system.top and system.gro does not match (O5 - O6)
    atom name 43 in system.top and system.gro does not match (O5 - O6)
    atom name 44 in system.top and system.gro does not match (H13 - H15)
    atom name 44 in system.top and system.gro does not match (H13 - H15)
3) if I visualize the .gro file with vmd, the positions of the atoms are pretty weird, they are all sitting on a straight line

**Comment by mattwthompson** [comment]
Hey @maxbonomi - super late so you may not need this any more, but much of the virtual site code has been rewritten and with release 0.3.14 and later, this should be supported. Part of the rewrite involves de-duplicating identical-seeming parameters by molecule, so the virtual site is only listed as an "atom type" once and, in general, identical molecules should only appear once. Much of the code - assigning vdW parameters and charges, virtual site geometries, and particle positions - uses the same code under the hood as the OpenMM export, so it's hopefully more reliable than my one-off attempt in the past.

This example uses a different four-site water model but you get the idea: https://github.com/openforcefield/openff-interchange/blob/v0.3.14/examples/ligand_in_water/ligand_in_water.ipynb

If https://github.com/openforcefield/openff-forcefields/pull/76 is completed, there'll be a SMIRNOFF port of TIP4P-EW, for now there's just OPC and TIP4P-FB

**Comment by mattwthompson** [comment]
This is online with recent (anything 2024, most of 2023) versions of the OpenFF stack: https://docs.openforcefield.org/en/latest/examples/openforcefield/openff-interchange/ligand_in_water/ligand_in_water.html#appendix-c-using-the-tip4p-fb-water-model-with-gromacs
