### ISSUE TITLE
About the support for openFF3

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-interchange#543]
**Description**
It has been some time since the openFF3 beta come out. I noticed that recently the interchange is beginning to support virtual site. I wonder if the current interchange would support generate molecule with openFF3 and write them to Gromacs/Amber topology? Thank you.

**Comment by mattwthompson** [comment]
Rosemary may or may not include virtual sites, but if it does, Interchange will fully support writing them out to OpenMM, GROMACS, and Amber to the best of our ability. All SMIRNOFF virtual sites are currently supported by the OpenMM export, some are supported in the GROMACS export (work in progress), and we are currently working on finding documentation for how Amber supports virtual sites.

Also keep in mind that Interchange can support virtual sites prior to them being included in a mainline force field if somebody writes up the appropriate SMIRNOFF data; that's what we do in the current examples
* https://github.com/openforcefield/openff-interchange/blob/v0.2.2/examples/ligand_in_water/ligand_in_water.ipynb
* https://github.com/openforcefield/openff-toolkit/blob/0.11.2/examples/virtual_sites/vsite_showcase.ipynb

**Comment by j-wags** [comment]
@xiki-tempula Thanks for writing in. Could you clarify which "OpenFF 3 beta" you're referring to? As far as I know we haven't released any beta force fields for the OpenFF 3.X.Y line, so we should probably correct some messaging if people think we've sent something like that out!

**Comment by xiki-tempula** [comment]
Had the discussion last Friday.
