### ISSUE TITLE
Potential error in LAMMPS improper atom order

### ISSUE THREAD

**Issue by benjamindjensen** [openforcefield/openff-interchange#544]
**Description**

Interchange appears to be defining impropers with the central atom in the second position in LAMMPS output files.

The expected atom order for impropers in LAMMPS with `improper_style cvff` is I,J,K,L where the improper dihedral angle is between the plane of I,J,K and the plane of J,K,L (https://docs.lammps.org/improper_cvff.html). The central atom in the improper is the first atom I. See the note in the documentation: _Note that defining 4 atoms to interact in this way, does not mean that bonds necessarily exist between I-J, J-K, or K-L, as they would in a linear dihedral. Normally, the bonds I-J, I-K, I-L would exist for an improper to be defined between the 4 atoms._

**Reproduction**

```
molecule = Molecule.from_smiles('C1=CN=CN1')
sage = ForceField("openff_unconstrained-2.0.0.offxml")
molecule.generate_conformers()
cubic_box = (
    np.array(
        [
            [10.0, 0.0, 0.0],
            [0.0, 10.0, 0.0],
            [0.0, 0.0, 10.0],
        ]
    )
    * unit.angstrom
)

interchange = Interchange.from_smirnoff(topology=[molecule], force_field=sage, box=cubic_box)
interchange.to_lammps("imidazole.lmp")
```

**Output**

```
Impropers

1	3	5	4	8	3
2	2	1	5	4	9
3	1	6	1	2	5
6	1	3	2	7	1
8	1	1	2	3	7
10	3	3	4	5	8
12	2	9	5	1	4
15	2	4	5	9	1
16	1	2	1	5	6
20	1	7	2	1	3
23	1	5	1	6	2
24	3	8	4	3	5
```

![image](https://user-images.githubusercontent.com/64032677/197202566-187b3a64-77fe-4bb6-80dd-11295cc1a47e.png)

**Software versions**
From `conda list`:
`openff-interchange        0.2.1              pyhd8ed1ab_0    conda-forge`

**Comment by mattwthompson** [comment]
Thanks for the detailed report! I've been confused about impropers for well over 5 years, so it's likely I did botch it here. If I'm reading the snippet of the data file correctly, it sure does look like the central atom is listed second when it should be first. Interestingly enough, the [internals already](https://github.com/openforcefield/openff-interchange/blob/v0.2.2/openff/interchange/interop/internal/lammps.py#L405) process the impropers with central-atom-first and central-atom-second orderings for other reasons, but chose to write them out with the wrong one. The fix here should be straightforward enough, I'll give it a spin shortly.

P.S. Please do not hesitate to raise issues about anything related to the LAMMPS export. I used LAMMPS extensively years ago but I don't use it day-to-day, nor does anybody else internally. So user feedback is especially useful here.

**Comment by mattwthompson** [comment]
Thanks again. I think for now we are only writing cvff as that's the only way I could find support for periodic impropers, which are most commonly used in bio sorts of work. This is good information for the future, though.


> I've been getting a lot of value out of OpenFF and have been getting reasonable results so far modeling aerospace epoxies. The automatic force field assignment greatly simplifies the modeling-building processes! Thank you for your part in making this possible.

Thank you very much! It's gratifying to see organic impact, especially in domains we did not necessarily design for.

**Comment by benjamindjensen** [comment]
> Thanks again. I think for now we are only writing cvff as that's the only way I could find support for periodic impropers, which are most commonly used in bio sorts of work. This is good information for the future, though.
> 
Yes, agreed that the LAMMPS CVFF form matches the OpenFF form for impropers, and is the correct improper style to match OpenFF.
