### ISSUE TITLE
Missing RESIDUE_LABEL flag in AMBER topology

### ISSUE THREAD

**Issue by lohedges** [openforcefield/openff-interchange#652]
Hello there,

I see that you have recently made edits to how the RESIDUE_LABEL flag is generated [here](https://github.com/openforcefield/openff-interchange/commit/6025b546c9fa96ae0d1dd763fcf31be56f559b46). The logic doesn't seem to be working correctly, resulting in a blank entry. For example, using:

```python
from openff.interchange import Interchange
from openff.toolkit.topology import Molecule
from openff.toolkit.typing.engines.smirnoff import ForceField

off_molecule = Molecule.from_smiles("C")
off_molecule.generate_conformers(n_conformers=1)

forcefield = ForceField("openff_unconstrained-2.0.0.offxml")

interchange = Interchange.from_smirnoff(
    force_field=forcefield, topology=off_molecule.to_topology()
)

interchange.to_prmtop("interchange.prmtop")
```

Gives the following `RESIDUE_LABEL` records:

__openff-interchange-base   0.2.3              pyhd8ed1ab_1    conda-forge__
```
%FLAG RESIDUE_LABEL
%FORMAT(20a4)
RES
```

__openff-interchange-base   0.3.0              pyhd8ed1ab_0    conda-forge__
```
%FLAG RESIDUE_LABEL
%FORMAT(20a4)

```

This is causing issues for our AMBER parser, which expects a label to be present. (See [here](https://github.com/OpenBioSim/sire/issues/42) for details.)

**Software versions**

- Linux
- Conda
- As above

**Comment by mattwthompson** [comment]
I'm not sure what's supposed to happen here, since there is no residue information in the input - a dummy `RES` in there never seemed satisfactory. If that's what you expect it can be added back.

**Comment by lohedges** [comment]
Ah, okay, I guess I misunderstood the change to the logic. Looking again it is clear that previously you only added the dummy `RES` label for single residue topologies. I had assumed that the `residue.residue_name` attribute wouldn't exist if the name was missing, in which case it would be assigned the default of `RES`.

It is easy to fix this at our end, but I'm not sure if there could be any other unintended consequences of a missing residue label. In our case we got a segfault since the number of labels that were parsed didn't match the number of `RESIDUE_POINTER` entries. The [format specification](https://ambermd.org/FileFormats.php) does imply that there should be `NRES` labels.

**Comment by mattwthompson** [comment]
Missing residue labels does seem worse than having garbage info there. This is something our infrastructure doesn't do great right now, unfortunately, so I'm in a position of deciding between different stopgaps. What was there before was not great but also not so bad that it caused segfaults - I think I'll try reverting back to the old behavior.

There's plenty more work to be done with the different cases to consider (the toolkit loads protein PDBs with residue information, but ligands won't have molecule names unless user-specified or in the file/object it's loaded from, and even then it's a bit of a hassle to squish together molecule and residue names) but we might have to push those into the future

**Comment by mattwthompson** [comment]
The whole Amber exporter is due for a rewrite but is at least a few weeks out. Until then, I think #655 fixes this specific case and probably avoids a blank RESIDUE_LABEL section. Could you have a look at it and let me know if that doesn't look correct?

**Comment by lohedges** [comment]
Thanks, that does the job. I guess there's an edge case if the topology contains a mixture of residues with and without names, but I'm not sure if this is even possible. I definitely feel your pain of dealing with all of the possible use cases and inputs. As you say, it's easy to end up with workarounds on top of workarounds, or deciding between different stopgap solutions.

**Comment by mattwthompson** [comment]
Thanks for the report. I've merged that fix, which will land in 0.3.1 in the next week or two.

Later we'll take a deeper dive into some of the many different ways these inputs can be structured. I don't think there will be an elegant way to handle them, it'll just take a lot of tests and branching logic.

**Comment by mattwthompson** [comment]
0.3.1 is released, packages should be online in an hour or so

**Comment by lohedges** [comment]
Thanks for letting me know. Much appreciated.
