### ISSUE TITLE
Saved Amber files when loaded report different non bonded energies

### ISSUE THREAD

**Issue by bieniekmateusz** [openforcefield/openff-interchange#682]
**Description**

I generated an Amber file after #676 and the non bonded energies do not agree with the original files. 
Here, I take the IG system and I turn it into .prm7 and then load it into OpenMM to show that it has different nonbonded energies:
```
---------------  ------------------  ------------------  --------------------  ------------------  ------------------
Name             HarmonicBondForce   HarmonicAngleForce  PeriodicTorsionForce  NonbondedForce      Total Energy
OFFXML->IG->OMM  4.97240194233043    112.06718710365426  5.962075505081159     16.131454431635195  139.13311898270103
IG Amber->OMM    4.9724014609325575  112.06719100050545  5.962075539523636     285.7017114200895   408.7033794210512
---------------  ------------------  ------------------  --------------------  ------------------  ------------------
```

**Reproduction**

[omm_exception_igamber_nb.zip](https://github.com/openforcefield/openff-interchange/files/11332922/omm_exception_igamber_nb.zip)

**Software versions**
- Interchange? Latest github version

**Comment by mattwthompson** [comment]
The [problem](https://gist.github.com/mattwthompson/2724002d4827e471147301f21088da7e) is in the exception parameters. I'm inclined to take the first row as correct:

```python
In [18]: get_openmm_energies(ig)["Nonbonded"].to(unit.kilocalorie_per_mole)
Out[18]: 16.16323571007663 <Unit('kilocalorie_per_mole')>
```

but, uhh, ...
```python
In [19]: get_summary_data(ig)
Out[19]:
              Bond       Angle    Torsion  Nonbonded            vdW  Electrostatics
OpenMM   20.804530  468.889111  24.945324  67.626978            NaN             NaN
Amber    20.804522  468.889165  24.945426        NaN  108618.148750     -118.034824
GROMACS  20.804855  468.889404  24.945323        NaN     147.760298      -80.150211
LAMMPS   20.804524  468.889123  24.945324        NaN     147.536650      -80.400669
```

I thought I had this difference tested somewhere, but obviously not. Fortunately this test is basically already written!

I did notice that the systems differ in the non-bonded settings; if using SMIRNOFF force fields through these sorts of pathways don't forget to update the cutoff and switching function. I think this can be done with something like `createSystem(nonbondedCutoff=9.0 * unit.angstrom, switchDistance=8.0 * unit.angstrom)`; I forget how to pass it through to Amber infrastructure but I recall it being supported one way or another. This is a more subtle difference but I wanted to bring it to your awareness; the force fields are trained with these settings so they (probably) perform best with them as well.

**Comment by stefdoerr** [comment]
I also read the prmtop file afterwards with `parmed` and got the following error after upgrading from 0.2.3 to 0.3.1
```
parmed.exceptions.MoleculeError: Cannot exclude an atom from itself! Atoms are: <Atom H8 [19]; In RES 0> <Atom H8 [19]; In RES 0>
```
Seems like there is a bug in exclusion writing?

**Comment by mattwthompson** [comment]
@stefdoerr thanks, definitely related, that looks similar to #676 / #680 which I thought I fixed but seems to have also introduced what started off this report. Still working on figuring out the root cause but I'm hoping to get it all sorted out soon

**Comment by mattwthompson** [comment]
This has been difficult to track down, but I think I have it resolved.


```
---------------  ------------------  ------------------  --------------------  ------------------  -----------------
Name             HarmonicBondForce   HarmonicAngleForce  PeriodicTorsionForce  NonbondedForce      Total Energy
OFFXML->IG->OMM  4.97240194233043    112.06718710365429  5.959231935849295     16.131454431635195  139.1302754134692
IG Amber->OMM    4.9724014609325575  112.06719100050546  5.959231971012451     16.131450313851364  139.1302747463018
---------------  ------------------  ------------------  --------------------  ------------------  -----------------
```

Something was funky in the logic with how 1-4 interactions were counted and then later excluded, made worse by how I don't understand what's supposed to be in the file. I'm going off of the [only documentation](https://ambermd.org/prmtop.pdf) I can find on this specific behavior; if anybody else is aware of other sources of information I'd gladly welcome more. In this case it describes well enough how to interpret what's in a file, but lacks enough information about how information is supposed to be processed while writing one.

Incidentally, I might have found a bigger issue with improper torsions. I suspect that will be a headache to knock out.

**Comment by bieniekmateusz** [comment]
I am afraid I don't any better documentation for the Amber format. I'll continue checking the results on other files so hopefully if there is an issue we'll pick that up. Thanks

**Comment by mattwthompson** [comment]
Part of the reason I was spinning my wheel yesterday was that I was using a set of Amber files loaded through OpenMM and ParmEd as the reference. I'm pretty confident that Interchange's OpenMM export gets things right but this is not so useful for discerning propers vs. impropers. OpenMM does not generally distinguish between propers and impropers (#623) and even though ParmEd [makes an attempt](https://github.com/ParmEd/ParmEd/blob/3.4.4/parmed/openmm/topsystem.py#L277) to do this, it was not getting caught. (The fourth atom in every dihedral of this Interchange -> OpenMM -> ParmEd pathway was positive, which is fine for energy calculations but not fine for quickly discerning which are impropers.) It occurred to me late last night that I can also go Interchange -> GROMACS -> ParmEd in hopes that propers and impropers are separated, since GROMACS clearly maintains that information. This file has the interesting property that all impropers (fourth atom negative) had their exclusions ignored:

```
%FLAG DIHEDRALS_INC_HYDROGEN
%FORMAT(10I8)
       0      12       9      21       1       3       6       9      21       2
       9       6       3      18       4      12       0       3      18       3
      15       0      12      24       3      15       0      12       9       3
      15       0       3      18       3      21       9      12      24       1
       6       9      12      24       1      15       0       3       6       3
       3       0      12      24       3       0      18      -6      -3       6
       0      12     -15      -3       6       0      15      -3     -12       6
       0       3     -12     -15       6       9       6     -12     -21       7
       9      21      -6     -12       7       9      12     -21      -6       7
       9       0     -24     -12       7       3       0      -6     -18       6
       0      24      -9     -12       7       6       0     -18      -3       6
      12       0      -9     -24       7
%FLAG DIHEDRALS_WITHOUT_HYDROGEN
%FORMAT(10I8)
       0      12      -9       6       1       3       0     -12       9       3
      12       0      -3       6       3       0       3      -6       9       4
       3       6      -9      12       5
```

I'm still unsure how 1-4 interactions could possible be counted in a dihedral given that the rest of the bond graph is probably set up correctly. But this makes energies pretty tight.

For the smallest molecule that reproduces my headaches (imidazole):
```
              Bond       Angle   Torsion  Electrostatics       vdW
OpenMM   18.619643  118.574111  0.000081      -12.643163 -1.172899
Amber    18.619637  118.574142  0.000000      -12.638190 -0.594546
GROMACS  18.620449  118.574234  0.000079      -12.712922 -0.594816
LAMMPS   18.619652  118.574104  0.000081      -12.741790 -0.598532
```

and for your ligand:
```
             Bond       Angle    Torsion  Electrostatics         vdW
OpenMM   9.053842  448.875637  55.236098      -98.128033  217.423954
Amber    9.053758  448.875838  55.235913      -98.129026  117.967462
GROMACS  9.053883  448.875610  55.236004      -98.278366  115.916903
LAMMPS   9.053837  448.875628  55.236100      -98.093671  115.717845
```

I'll need to look more closely into the OpenMM energy difference, it could be as simple as i.e. how the 1-4 and intermolecular vdW interactions are grouped together.

[Here's](https://gist.github.com/mattwthompson/62237fd47b0f99cd651d640cfbfb2490) what I'm using to work through this in case anybody (including my future self) needs to reproduce this.

**Comment by mattwthompson** [comment]
#685 fixes this, or at least the issue with this specific molecule. I'm not confident there aren't other issues with some combination of non-bonded exceptions, propers, and impropers. We can pick away at those as they come up.

**Comment by stefdoerr** [comment]
Can you ping here please once a new version is out on conda-forge? Thanks for the fix!

**Comment by mattwthompson** [comment]
Hey @stefdoerr - 0.3.2 is online now, hope it helps!

**Comment by bieniekmateusz** [comment]
Thanks so much! All the SYK ligands now have the same energies whether it is translated into Amber or directly into OpenMM.

**Comment by mattwthompson** [comment]
Awesome! Thanks for your help here.
