### ISSUE TITLE
Make OpenMM an optional dependency

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#722]
**Description**
The toolkit already has this; it would be useful to do the same here.

**Comment by SimonBoothroyd** [comment]
+1 for this so we can parameterize on linux without pulling all of CUDA down!

@mattwthompson what would be the blockers here?

**Comment by mattwthompson** [comment]
I don't think there are major blockers, this should mostly be a matter of doing all of the necessary housekeeping (decorators, safe imports, etc.). If I run into anything I'll update this issue and solicit some help.

The blocker used to be `openmm` being in the toolkit's base recipe, which you've probably already seen is [no longer there](https://github.com/conda-forge/openff-toolkit-feedstock/blob/8579d1cdd65ce0be55d8e3602e7ca90d6714412d/recipe/meta.yaml#L17-L42)

**Comment by mattwthompson** [comment]
This should be included in 0.3.12

**Comment by SimonBoothroyd** [comment]
Fantastic work, thanks @mattwthompson!
