### ISSUE TITLE
 Make custom exceptions subclass Exception rather than BaseException

### ISSUE THREAD

**Issue by Dunni3** [openforcefield/openff-interchange#747]
Most of the custom exceptions defined in `openff/interchange/exceptions.py` subclass the `BaseException `class. I propose that they be modified to instead subclass the `Exception` class.

Inherting from `BaseException` can create issues for users. For example, if you wanted to catch errors that may occur when building an interchange, the typical user would do something like this:

```python
try:
    interchange = Interchange.from_smirnoff(forcefield, topology)
except Exception:
    exception_handling_function()
```

The above code would fail to catch most of the exceptions that could be raised by openff-interchange. While you could technically get around this by using a `except BaseException` statement instead, this is a non-standard practice that most users would not know to do. Moreover, [python library docs](https://docs.python.org/3/library/exceptions.html#BaseException) explicitly advise against using `BaseException` directly. All user-implemented exceptions should instead subclass the `Exception` class.

**Comment by mattwthompson** [comment]
I think you're right. This was an oversight on my part. Thanks for pointing this out!
