### ISSUE TITLE
Add link to Interchange docs in About section?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-interchange#768]
**Description**
The About section on the [github page](https://github.com/openforcefield/openff-interchange) currently does not link to docs.
It would help users navigate if we could add a link to relevant Interchange docs, such as https://docs.openforcefield.org/projects/interchange/en/stable/using/intro.html
![image](https://github.com/openforcefield/openff-interchange/assets/3656088/70604b92-9781-4763-91c8-886921e53b39)

**Comment by mattwthompson** [comment]
Good idea, thanks! I've also added a couple of tags that might help wayward explorers nagivate here

![image](https://github.com/openforcefield/openff-interchange/assets/7935382/a5f95dd9-b813-4006-ae88-d4f926905efd)
