### ISSUE TITLE
Zenodo spelling of "Interchannge"

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-interchange#790]
**Description**
This might not be the best place to raise it, but I'm not sure where else -- the Zenodo record of Interchange seems to have too many "n"s. Is it possible to change this record, or are we stuck with the spelling?

**Reproduction**

https://zenodo.org/record/8244803

**Output**

Please include the output, including full tracebacks of any errors, resulting from the reproduction.

**Software versions**

- Which operating system and version are you using?
- How did you install Interchange?
- What is the output of running `conda list`?

**Comment by mattwthompson** [comment]
I fixed it in a previous version by manually creating a new release, but it looks like newer releases are picking up on the typo again?

https://zenodo.org/record/8179774

**Comment by mattwthompson** [comment]
At this point I wonder if it's easier to try to nuke it, scrub the record with a typo, and replace it with a totally new record ...

**Comment by mattwthompson** [comment]
It looks like I can force it to forget about the initial state:

<img width="1526" alt="image" src="https://github.com/openforcefield/openff-interchange/assets/7935382/58ec1179-30da-41cd-ae9d-6d3922c988a6">


I'll give this a try.

**Comment by mattwthompson** [comment]
Ahh, no! The typo stems from the citation file in the repo!

https://github.com/openforcefield/openff-interchange/blob/fdf7630d809859eb9e4a4b36c93a11aef736eee9/CITATION.cff#L6

**Comment by mattwthompson** [comment]
Possibly fixed in https://github.com/openforcefield/openff-interchange/commit/01bc3e97f11dac1bd8543eefd9852c674c425077; if this persists through to the next release I'll have to do something more drastic.

**Comment by lilyminium** [comment]
Thanks @mattwthompson!

**Comment by mattwthompson** [comment]
Seems to have worked with the 0.3.13 release: https://zenodo.org/record/8274558

<img width="1031" alt="image" src="https://github.com/openforcefield/openff-interchange/assets/7935382/3566401a-7bc3-43cf-9ece-4ffebbc1a265">

Thanks for noticing this!
