### ISSUE TITLE
Interchange overwrites charges when virtual sites are present

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-interchange#792]
**Description**
I tried to create a simulation with OpenMM using a force field that contains virtual sites. I expect this virtual site to get applied with the increments as *additional* to whatever electrostatics exist already, instead of replacing. However, it appears to simply replace the charge: https://github.com/openforcefield/openff-interchange/blob/01bc3e97f11dac1bd8543eefd9852c674c425077/openff/interchange/smirnoff/_nonbonded.py#L387-L393

This is a diversion of behaviour from the original / older implementation I'm currently using to train the FF:

```
  openff-bespokefit        0.1.1      pyhd8ed1ab_0  conda-forge
  openff-evaluator         0.3.11     pyhd8ed1ab_0  conda-forge
  openff-evaluator-base    0.3.11     pyhd8ed1ab_0  conda-forge
  openff-forcefields       2023.06.0  pyh1a96a4e_0  conda-forge
  openff-fragmenter-base   0.1.2      pyhd8ed1ab_1  conda-forge
  openff-interchange-base  0.1.4      pyheb06c22_0  conda-forge
  openff-qcsubmit          0.3.2      pyhd8ed1ab_0  conda-forge
  openff-recharge          0.3.4      pyhd8ed1ab_1  conda-forge
  openff-toolkit           0.10.7     pyhd8ed1ab_0  conda-forge
  openff-toolkit-base      0.10.7     pyhd8ed1ab_0  conda-forge
  openff-units             0.2.0      pyh1a96a4e_1  conda-forge
  openff-utilities         0.1.3      pyh6c4a22f_0  conda-forge
```

**Reproduction**

Sorry, a bit long --

```
import openmm
from openff.toolkit.topology import Molecule
from openff.toolkit.typing.engines.smirnoff import ForceField

ccbr = Molecule.from_smiles("CCBr")
ff = ForceField("vsite-ff.offxml", allow_cosmetic_attributes=True)

interchange = ff.create_interchange(ccbr.to_topology())
elec = interchange.collections["Electrostatics"]
charges = [x.m for x in elec.charges.values()]
charges
```
```
[-0.036175000946968794,  # C
 0.14386426704004407,  # C
 -0.29532093880698085,  # Br
 0.028418336529284716,
 0.028418336529284716,
 0.028418336529284716,
 0.05118833156302571,
 0.05118833156302571]
```
```
vsite_potential = list(elec.potentials.values())[-1]
print("vsite potential", vsite_potential)
```
```
vsite potential parameters={'charge_increments': <Quantity([-0.08173966  0.        ], 'elementary_charge')>} map_key=None
```
```
vsite_charges = [x.m for x in elec.charges_with_virtual_sites.values()]
vsite_charges
```
```
[-0.036175000946968794,  # C
 0.0,  # C
 -0.08173965662717819,  # Br
 0.028418336529284716,
 0.028418336529284716,
 0.028418336529284716,
 0.05118833156302571,
 0.05118833156302571,
 0.08173965662717819]  # virtual site
```

In my other environment with the older toolkit, I get the charges I expect:
```
ccbr = Molecule.from_smiles("CCBr")
ff = ForceField("vsite-ff.offxml", allow_cosmetic_attributes=True)
system = ff.create_openmm_system(ccbr.to_topology())
nbforce = [f for f in system.getForces() if isinstance(f, openmm.NonbondedForce)][0]
omm_charges = []

for i in range(system.getNumParticles()):
    a, b, c = nbforce.getParticleParameters(i)
    omm_charges.append(a.value_in_unit(openmm.unit.elementary_charge))
omm_charges
```
```
[-0.036175000946968794,  # C
 0.14386426704004407,  # C
 -0.37706059543415904,  # Br
 0.028418336529284716,
 0.028418336529284716,
 0.028418336529284716,
 0.05118833156302571,
 0.05118833156302571,
 0.08173965662717819]  # virtual site
```

**Software versions**

- Which operating system and version are you using?
- How did you install Interchange?
- What is the output of running `conda list`?

```
import openff.interchange
openff.interchange.__version__
'v0.3.7'
```
[vsite-ff.offxml.txt](https://github.com/openforcefield/openff-interchange/files/12373483/vsite-ff.offxml.txt)

**Comment by mattwthompson** [comment]
Well that certainly doesn't look ideal. I wonder if I simply meant

```
             returned_charges[index] += charge 

```
?

**Comment by lilyminium** [comment]
On second look, I don't think the issue is actually with that part of the code, sorry -- that looks like it's just choosing between the type of the key in the returned charges dictionary.

**Comment by mattwthompson** [comment]
Some versions of that code allowed indices to be ints, others allowed them to be some sort of key object or mixtures thereof. That's what tipped me off to something being wrong, in addition to the toggle seemingly setting the charges to be equal to the increments instead of incrementing them.

**Comment by mattwthompson** [comment]
I wonder if it even makes sense to have that `include_virtual_sites` argument.

If there aren't virtual sites, the argument doesn't matter.

If there are virtual sites, would you really want to get the charge on only the atomic particles? They'd either not add up to the neutral charge of the molecule or only represent a part of the force field.

**Comment by lilyminium** [comment]
I'd think the original atom charges should generally add up to the molecular charge independently of the virtual sites, right? The vsites here just add increments that redistribute the charge and should ultimately add up to 0. 

> only represent a part of the force field

It makes sense this to me that this would be generally less desirable, and that we should tell people who can't use vsites to just use a different FF. I'm looking at these mostly for diagnostic/debugging purposes, so it'd be nice to keep it around just for that, but otherwise I can't think of a very compelling use case off the top of my head.

**Comment by mattwthompson** [comment]
> I'd think the original atom charges should generally add up to the molecular charge independently of the virtual sites, right?

Right, I'm assuming that without virtual sites, the net charge is 0 or some integer. I guess that's not a hard requirement, I'm just using that as a comparison to the behavior of `include_virtual_sites=False` while a force field does have virtual sites that modify charges.

I think we're on the same page in that it doesn't make much sense to get "what if this force field didn't have charge-applying virtual sites" charges - I might remove that from the public interface but keep a way for you and others to dig into that behavior anyway.

**Comment by mattwthompson** [comment]
I took a look at this today; something is fairly borked with the internals. I can't get to the bottom of it, but it relates to my assumption that [this attribute](https://github.com/openforcefield/openff-interchange/blob/005a96c275603dd1e75bebcc6dc1671b203fe188/openff/interchange/common/_nonbonded.py#L89-L92) is an empty dict when initialized, something that seems intuitive and is reflected in an interpretive session.

If I'm still stuck tomorrow morning when I look at this with fresh eyes, I'll detail my confusion more exhaustively and ask for help.

**Comment by mattwthompson** [comment]
Cool, so the problem was [here](https://github.com/openforcefield/openff-interchange/blob/c292de8b32852fb4926feab5c952a56501f4c315/openff/interchange/smirnoff/_nonbonded.py#L336-L338) when applying the virtual site's charge increments to the orientation atom indices, I was keying by `TopologyKey` when everywhere else I was using ints for atoms. (`VirtualSiteKey` is used to key the charge actually carried by the virtual site; it all gets confusing to me since an earlier version of this function used an unholy mixture of ints and `TopologyKey`s for atoms.)

**Comment by mattwthompson** [comment]
#797 fixes this - or at least I get

```python
[-0.036175000946968794,
 0.14386426704004407,
 -0.37706059543415904,
 0.028418336529284716,
 0.028418336529284716,
 0.028418336529284716,
 0.05118833156302571,
 0.05118833156302571,
 0.08173965662717819]
```
locally. I also made `.charges` return charges with virtual sites (including the virtual particle, and appropriately applying its charge increments). `._charges_without_virtual_sites` exists, as a private method, in case that's useful. Right now it applies the charge increments but does not include the virtual particle in the returned value. If desired it could be updated to just not apply the charge increments - I have no preference either way.

It's hard to think about how this could be prevented. In principle, using a special dictionary that only accepts particular types as keys or values (maybe something that could be grabbed from the type annotation) might work, as would implementing this with fewer possible types filling those fields.
