### ISSUE TITLE
Warning message for vdWHandler mentions BondHandler

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-interchange#801]
**Description**

This warning is a bit surprising: https://github.com/openforcefield/openff-interchange/blob/8c12453ddf1738d7aee404acd5c34b61d42e6873/openff/interchange/smirnoff/_nonbonded.py#L107

```
/lila/home/lilywang/micromamba/envs/fb-195-tk-014-py310/lib/python3.10/site-packages/openff/interchange/smirnoff/_create.py:237: UserWarning: Automatically down-converting BondHandler from version 0.4 to 0.3. In the future, this down-conversion will not happen and verison 0.3 will not be supported.
  _downconvert_vdw_handler(force_field["vdW"])
```
Should that be the vdwHandler instead?

Also, a small typo -- verison should be version: https://github.com/openforcefield/openff-interchange/blob/8c12453ddf1738d7aee404acd5c34b61d42e6873/openff/interchange/smirnoff/_nonbonded.py#L108

**Comment by mattwthompson** [comment]
Thanks for reporting, I'm bad at letting these slip in without reviews
