### ISSUE TITLE
Use structured data in LAMMPS driver

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-interchange#805]
**Description**
LAMMPS at some point in time improved how their log files are structured, in particular [using YAML outputs](https://docs.lammps.org/thermo_style.html) in some places. This might be easier to deal with than throwing around text files like I used to do back in the day.

**Comment by timbernat** [comment]
Alternately, one could also make use of the LAMMPS python API (specifically the [get_thermo() method](https://docs.lammps.org/Python_module.html#lammps.lammps.get_thermo)) and avoid parsing log file text altogether. I have a [basic implementation of this mechanism in my own package[(https://github.com/timbernat/polymerist/blob/dev/lammpstools/lammpseval.py#L72-L87) which only requires reading an input file (which can easily be produced from and Interchange using MDConfig

**Comment by mattwthompson** [comment]
Wow, thanks - I didn't know their Python wrapper was so powerful. (Maybe I have bad memories trying to build it a decade ago)

```python
In [1]: import lammps

In [2]: wrapper = lammps.lammps()
LAMMPS (21 Nov 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task

In [3]: wrapper.file("tmp.in")
Reading data file ...
<SNIP>

In [4]: wrapper.last_thermo()
Out[4]:
{'E_bond': 0.6693447327557421,
 'E_angle': 5.421066567990172,
 'E_dihed': 29.942338413279195,
 'E_impro': 0.0,
 'E_pair': 4.391198970972843,
 'E_vdwl': 3.063124265386531,
 'E_coul': 8.296528734676809,
 'E_long': -6.968454029090497,
 'E_tail': -0.0014512577854809076,
 'PotEng': 40.42394868499795}

**Comment by mattwthompson** [comment]
I think this was taken care of in #903
