### ISSUE TITLE
Expose ``SMIRNOFFXXX`` classes through public API

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#807]
**Description**

The family of ``SMIRNOFFXXX`` classes (e.g. ``SMIRNOFFBondCollection``, ``SMIRNOFFAngleCollection``) are currently returned to the user via interchange objects, but the classes aren't technically 'visible' via the public API that I can see.

This seems like a slight idiosyncrasy in general, but in my case means if I try to do something with one of these in a function (for example compute an energy) I need to use an 'internal' type as a type hint which makes my linter complain.

**Comment by mattwthompson** [comment]
Hmm, I have them "private" so I can muck around with them and not officially break the API ... but I see how that's arguably a lost cause given where they're exposed in the core object.

**Comment by SimonBoothroyd** [comment]
Yeah I can definitely understand the hesitation there! But thanks, looks like this was nicely closed by #815
