### ISSUE TITLE
Virtual Site Parameters Don't Store Type

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#808]
**Description**

As far as I can tell virtual site parameters or their associated potential keys don't store what type of v-site the parameter is for. It seems that for now it has to be inferred from the topology key.

This makes it harder to parse what the v-site parameter actually corresponds to, and presumably can run into situations where multiple v-site parameters have the same SMIRKS, name, and match but different type, but are treated identical by interchange.

**Comment by mattwthompson** [comment]
Does `VirtualSiteKey.type` handle the information you need to keep track here?

Using your snippet from #812 in my interpreter history:

```python
In [2]: interchange["VirtualSites"]
Out[2]: Handler 'VirtualSites' with expression '', 1 mapping keys, and 1 potentials

In [3]: [key.type for key in interchange["VirtualSites"].key_map]
Out[3]: ['BondCharge']

**Comment by SimonBoothroyd** [comment]
It does, but it would probably be useful for the potential to track it as it as part of the parameter definition itself, rather than something that comes out of applying the parameter to a topology. 

Currently I [infer it from the topology key](https://github.com/SimonBoothroyd/smee/blob/62bf8e358c83911eafa5b442b0498c9c2260aa3f/smee/ff/_ff.py#L291-L297) like you suggest, but this feels a bit fragile.

**Comment by mattwthompson** [comment]
I see - I think that's fair, and I hadn't really considered that that information would be needed at that point.

The quickest fix would be to just slap on another field

```diff
diff --git a/openff/interchange/models.py b/openff/interchange/models.py
index e3fd6daa..da3dd1e8 100644
--- a/openff/interchange/models.py
+++ b/openff/interchange/models.py
@@ -284,6 +284,10 @@ class PotentialKey(DefaultModel):
         description="If this is a key to a WrappedPotential interpolating multiple parameter(s), "
         "the bond order determining the coefficients of the wrapped potentials.",
     )
+    virtual_site_type: Optional[str] = Field(
+        None,
+        description="The 'type' of virtual site (i.e. `BondCharge`) this parameter is associated with.",
+    )
 
     def __hash__(self) -> int:
         return hash((self.id, self.mult, self.associated_handler, self.bond_order))
```

(A sludgier fix would be to append it to the `id` string.) I think this might be a good time to split out this class into more specific ones for each use case, similar to how `TopologyKey` now has some more descriptive subclasses.

**Comment by SimonBoothroyd** [comment]
> I think this might be a good time to split out this class into more specific ones for each use case, similar to how TopologyKey now has some more descriptive subclasses.

That sounds reasonable!
