### ISSUE TITLE
OpenMM v-site ordering does not match ``virtual_site_key_topology_index_map``

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#810]
**Description**

When going from an interchange containing two water molecules, each with a v-site, to OpenMM, the v-sites are placed after each molecule (i.e. with indices of 3, 7). The interchange object (and particularly the `virtual_site_key_topology_index_map` attribute of the v-site handler) state they should have indices 6, and 7.

**Reproduction**

```
molecule_a = openff.toolkit.Molecule.from_smiles("O")
molecule_a.generate_conformers(n_conformers=1)
molecule_b = openff.toolkit.Molecule.from_smiles("O")
molecule_b.generate_conformers(n_conformers=1)

topology = openff.toolkit.Topology()
topology.add_molecule(molecule_a)
topology.add_molecule(molecule_b)

interchange = openff.interchange.Interchange.from_smirnoff(
    openff.toolkit.ForceField("tip4p_fb.offxml"), topology
)
```

**Output**

Please include the output, including full tracebacks of any errors, resulting from the reproduction.

**Software versions**

- Which operating system and version are you using? OSX
- How did you install Interchange? conda
- What is the output of running `conda list`? `openff-interchange-base   0.3.14`

**Comment by j-wags** [comment]
Thanks for the detailed reports, @SimonBoothroyd - Matt's out this week but he'll be able to take a look when he returns!

**Comment by mattwthompson** [comment]
Wow - nice find! It looks like the indexing switched to per-molecule collated at the OpenMM layer. All of the checks were for consistency within the OpenMM layer, so no alarm bells were sounded.

**Comment by mattwthompson** [comment]
I think #816 changed this to be what you expect - here's what I understand that to mean

```python
In [1]: import openff.toolkit
   ...: import openff.interchange

In [2]: molecule_a = openff.toolkit.Molecule.from_smiles("O")
   ...: molecule_a.generate_conformers(n_conformers=1)
   ...: molecule_b = openff.toolkit.Molecule.from_smiles("O")
   ...: molecule_b.generate_conformers(n_conformers=1)
   ...:
   ...: topology = openff.toolkit.Topology()
   ...: topology.add_molecule(molecule_a)
   ...: topology.add_molecule(molecule_b)
   ...:
   ...: interchange = openff.interchange.Interchange.from_smirnoff(
   ...:     openff.toolkit.ForceField("tip4p_fb.offxml"), topology
   ...: )

/Users/mattthompson/mambaforge/envs/openff-interchange-dev/lib/python3.11/site-packages/smirnoff99frosst/smirnoff99frosst.py:11: UserWarning: Module openff was already imported from None, but /Users/mattthompson/software/openff-interchange is being added to sys.path
  from pkg_resources import resource_filename

In [3]: system = interchange.to_openmm()

In [4]: for index in range(6, 8):
   ...:     system.getVirtualSite(index)
   ...:     # Runs with no exceptions if particles are O H H O H H V V
   ...:
   ...: for index in range(8):
   ...:     print(index, system.getParticleMass(index))
0 15.99943 Da
1 1.007947 Da
2 1.007947 Da
3 15.99943 Da
4 1.007947 Da
5 1.007947 Da
6 0.0 Da
7 0.0 Da

**Comment by SimonBoothroyd** [comment]
I think that looks right! So long as `virtual_site_key_topology_index_map` points to the v-site (whether that be interleaved or at the end) then I think we're good!

**Comment by mattwthompson** [comment]
Great, this'll be in 0.3.15 soon
