### ISSUE TITLE
`scale_12` attr missing from non-bonded handlers

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-interchange#811]
**Description**

It looks like only the 1-3, 1-4, and 1-5 parameters are captured

**Comment by mattwthompson** [comment]
In think you're right - not intentional, though it'd be interesting to see if it's ever non-zero!

**Comment by mattwthompson** [comment]
It turns out the toolkit doesn't allow non-standard values of 1-2, 1-3, or 1-5 scaling, but still worth tracking

**Comment by SimonBoothroyd** [comment]
Nice, thanks!
