### ISSUE TITLE
Example view selection water

### ISSUE THREAD

**Issue by euhruska** [openforcefield/openff-interchange#819]
**Description**

In example "Solvating and equilibrating a ligand in a box of water" Appendix A the selection 'water' in
 `view.add_representation("licorice", selection="water")` doesn't work since the residue names are not set/UNK. Setting the residue names of water to 'HOH' fixes this issue:
```
for atom in water.atoms:
    atom.metadata["residue_name"] = "HOH"
```

**Reproduction**

Colab link in docs.

**Comment by mattwthompson** [comment]
Hey @euhruska - thanks for bringing this to our attention. It sounds like you're coming from this link? https://docs.openforcefield.org/en/latest/examples/openforcefield/openff-interchange/ligand_in_water/ligand_in_water.html

**Comment by euhruska** [comment]
Yes

**Comment by mattwthompson** [comment]
Thanks! For whatever reason, this looked fine locally for me and we haven't necessarily checked all notebooks top-to-bottom in their Colab versions. Adding your suggestion fixes it in my instance, so I expect it'll work
