### ISSUE TITLE
to_openmm `combine_nonbonded_forces` docstring default out-of-date

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-interchange#840]
**Description**

Just passing by and noticed a kwarg default was out-of-date in the docstring:

https://github.com/openforcefield/openff-interchange/blob/d5ecdb7e6def38984fb213eed4929d21f5609a47/openff/interchange/components/interchange.py#L410-L419

**Comment by mattwthompson** [comment]
Thanks! I thought `pydocstyle` detected this mismatch, but now I'm not so sure ...
