### ISSUE TITLE
`experimental/openmmforcefields/gaff.ipynb` and `ligand_in_water.ipynb` notebooks broken on OpenFF Docs

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-interchange#941]
I've gotten the OpenFF docs examples running again by manually skipping notebooks that were failing. This includes Interchange's `experimental/openmmforcefields/gaff.ipynb` and `ligand_in_water.ipynb` examples. Just dropping you a line to say that they don't seem to be working.

The environment used is here: https://github.com/openforcefield/openff-docs/blob/main/devtools/conda-envs/examples_env.yml

The list of skipped notebooks is here: https://github.com/openforcefield/openff-docs/blob/383a326bcae4154c9066b20aa925b407f288e14c/source/_ext/cookbook/globals_.py#L84

The goal is to set it up so that broken notebooks are automatically detected and don't block rendering other notebooks, but for now we're just manually specifying notebooks to skip.

**Comment by mattwthompson** [comment]
Thanks for the report - I think we've fixed this up now
